// Builds the flags from the inputs kept in data-sources/ and the flag sets in node_modules, with no network and no
// browser:
//
//   pnpm data            writes src/flags/<code>.ts, src/data/*.data.ts, the docs that list the flags, and the
//                        credits and licences in NOTICE.md
//
// For every code Kuni knows (each country, and the first level of the countries in SUBDIVISION_COUNTRIES):
//
//   1. the Commons file Wikidata names as its flag (scripts/select.ts), or the reason there is none, checked
//      against the SHA-256 the Commons snapshot recorded: the reference drawing, at the flag's true proportions;
//   2. the drawing chosen to ship, from scripts/choices.data.json (written by `pnpm data:choose`, which compares
//      Commons' drawing with flag-icons', country-flag-icons' and circle-flags' in a browser): Commons', or a
//      set's where it is the same flag at the same proportions and smaller, or free where Commons' is not;
//   3. that drawing optimised and made safe to inline (scripts/optimise.ts) at the precision the choice records,
//      and measured against the size budget.
//
// Places that share one drawing (Guadeloupe and France, Bouvet Island and Norway) share one picture: the flag's
// own module carries it and the other re-exports it. Run twice, it leaves the tree as it was.

import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";

import { subdivision as kuniSubdivision } from "@johnmorrisdotca/kuni/subdivisions";

import { setCandidates, setNamed } from "./candidates.ts";
import type { SourceName } from "./candidates.ts";
import { ACCEPTED, BUDGET_BYTES, CEILING_BYTES, FOCUS, NO_FLAG, REVIEWED, SAME_PLACE, SUBDIVISION_COUNTRIES, VARIANTS } from "./data-config.ts";
import type { Anchor } from "./data-config.ts";
import { classify, restrictionsOf } from "./licence.ts";
import type { Licence } from "./licence.ts";
import { optimiseFlag } from "./optimise.ts";
import type { Optimised } from "./optimise.ts";
import { places as allPlaces } from "./places.ts";
import type { Group, Place } from "./places.ts";
import { selectPlace } from "./select.ts";
import type { WikidataSnapshot } from "./select.ts";
import { readManifest, readSource, ROOT, sha256, SOURCES_DIR } from "./sources.ts";

interface CommonsFile {
  file: string;
  page: string;
  url: string;
  bytes: number;
  width: number;
  height: number;
  mime: string;
  uploaded: string;
  sha1: string;
  sha256: string;
  stored: string;
  metadata: Record<string, string>;
  templates: string[];
}

interface CommonsSnapshot {
  read: string;
  files: CommonsFile[];
}

interface Choice {
  source: Exclude<SourceName, "circle-flags"> | null;
  file?: string;
  precision?: number;
  keepPaths?: boolean;
  stubborn?: boolean;
  why: string;
  compared: Record<string, { design: number; same?: number; bytes?: number }>;
  designDiffers?: string[];
}

type ShippedLicence = { kind: "public-domain" | "cc0" | "cc-by" | "mit" | "accepted"; name: string; url: string | null };

interface Drawing {
  key: string; // "commons:Flag of Japan.svg", "country-flag-icons:3x2/YE.svg"
  source: Exclude<SourceName, "circle-flags">;
  file: string;
  page: string;
  version: string | null; // A set's version; null for Commons
  licence: ShippedLicence;
  author: string | null;
  credit: string | null;
  attributionRequired: boolean;
  templates: string[];
  uploaded: string | null;
  bytes: number; // As the source has it
  text: string;
}

interface Shipped {
  place: Place;
  drawing: Drawing;
  reference: CommonsFile; // The Commons file Wikidata names: the reference for the design and its proportions
  referenceLicence: Licence;
  item: string;
  optimised: Optimised;
  owner: string; // The code whose module carries the picture: its own, or the one it shares a drawing with
  gzip: number;
  why: string;
  compared: Choice["compared"];
  designDiffers: string[];
}

interface LeftOut {
  place: Place;
  kind: "no-flag" | "not-svg" | "licence";
  reason: string;
  file?: CommonsFile;
  licence?: Licence;
}

const report = process.argv.includes("--report");
const FLAGS_DIR = join(ROOT, "src", "flags");
const DATA_DIR = join(ROOT, "src", "data");
const HEADER = "// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.";
const KB = (bytes: number): string => (bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KB`);
const moduleName = (code: string): string => code.toLowerCase();
// Countries first, by code, then the subdivisions by code: AT-…, AU-…, BR-…, CA-….
const byCode = (a: { place: Place }, b: { place: Place }): number =>
  Number(a.place.group !== "country") - Number(b.place.group !== "country") || (a.place.code < b.place.code ? -1 : a.place.code > b.place.code ? 1 : 0);
const size = (one: Shipped): number => Buffer.byteLength(one.optimised.svg);

// 1. The inputs, each checked against sources.json, and the choices.
const manifest = readManifest();
const sourceNamed = (pattern: RegExp): string => {
  const entry = manifest.files.find((file) => pattern.test(file.path));
  if (entry === undefined) throw new Error(`no ${pattern} in data-sources/sources.json`);

  return readSource(manifest, entry.path).text;
};
const wikidata = JSON.parse(sourceNamed(/^wikidata-\d{4}-\d{2}-\d{2}\.json$/)) as WikidataSnapshot & { read: string };
const commons = JSON.parse(sourceNamed(/^commons-\d{4}-\d{2}-\d{2}\.json$/)) as CommonsSnapshot;
const commonsByFile = new Map(commons.files.map((file) => [file.file, file]));
const CHOICES = JSON.parse(readFileSync(join(ROOT, "scripts", "choices.data.json"), "utf8")) as Record<string, Choice>;

// 2. The places, from Kuni.
const places = allPlaces();
for (const place of places) if (place.group !== "country" && kuniSubdivision(place.code) === null) throw new Error(`Kuni does not know ${place.code}`);

const commonsText = (file: CommonsFile): string => {
  const bytes = readFileSync(join(SOURCES_DIR, file.stored));
  if (sha256(bytes) !== file.sha256) throw new Error(`data-sources/${file.stored} is not the file the Commons snapshot recorded`);

  return bytes.toString("utf8");
};

// A Commons file's licence, with the maintainer's decisions in data-config.ts laid over it.
const licenceOf = (file: CommonsFile): Licence => {
  const classified = classify(file.metadata, file.templates);
  const decision = ACCEPTED[file.file];
  if (classified.shipped || decision === undefined) return classified;

  return { shipped: true, kind: classified.publicDomainTemplate ? "public-domain" : "accepted", name: `${classified.name} (accepted: ${decision})`, url: classified.url };
};

// The drawing a choice names, with what is known about where it comes from and its terms.
const drawingOf = (place: Place, choice: Choice, reference: CommonsFile, referenceLicence: Licence): Drawing => {
  if (choice.source === "commons") {
    if (choice.file !== reference.file) throw new Error(`${place.code}: choices.data.json names ${choice.file}, but Wikidata names ${reference.file}: run pnpm data:choose ${place.code}`);
    if (!referenceLicence.shipped) throw new Error(`${place.code}: choices.data.json ships Commons' file, whose licence is ${referenceLicence.name}`);
    const metadata = reference.metadata;
    return {
      key: `commons:${reference.file}`,
      source: "commons",
      file: reference.file,
      page: reference.page,
      version: null,
      licence: { kind: referenceLicence.kind, name: referenceLicence.name, url: referenceLicence.url },
      author: metadata.Artist ?? null,
      credit: metadata.Credit ?? null,
      attributionRequired: metadata.AttributionRequired === "true",
      templates: reference.templates.map((template) => template.replace(/^Template:/, "")),
      uploaded: reference.uploaded.slice(0, 10),
      bytes: reference.bytes,
      text: commonsText(reference),
    };
  }
  const candidate = setCandidates(place.code).find((one) => one.source === choice.source && one.file === choice.file);
  if (candidate === undefined) throw new Error(`${place.code}: ${choice.source} has no ${choice.file}: run pnpm data:choose ${place.code}`);
  const set = setNamed(candidate.source);

  return {
    key: `${candidate.source}:${candidate.file}`,
    source: choice.source!,
    file: candidate.file,
    page: candidate.page,
    version: set.version,
    licence: { kind: "mit", name: "MIT", url: `https://cdn.jsdelivr.net/npm/${set.name}@${set.version}/LICENSE` },
    author: set.copyright,
    credit: `${set.name} ${set.version}, ${set.home}`,
    attributionRequired: true,
    templates: [],
    uploaded: null,
    bytes: Buffer.byteLength(candidate.text),
    text: candidate.text,
  };
};

// 3. Each place's flag, or why it has none.
const shipped: Shipped[] = [];
const leftOut: LeftOut[] = [];
const chosen: { place: Place; drawing: Drawing; reference: CommonsFile; referenceLicence: Licence; item: string; choice: Choice; named?: string }[] = [];
for (const place of places) {
  const selection = selectPlace(place.code, wikidata);
  const handWritten = NO_FLAG[place.code];
  if (handWritten !== undefined) {
    leftOut.push({ place, kind: "no-flag", reason: handWritten });
    continue;
  }
  if (selection.file === null) {
    leftOut.push({ place, kind: "no-flag", reason: selection.reason });
    continue;
  }
  const reference = commonsByFile.get(selection.file);
  if (reference === undefined) throw new Error(`${place.code}: ${selection.file} is not in the Commons snapshot: run pnpm data:commons`);
  if (reference.mime !== "image/svg+xml") {
    leftOut.push({ place, kind: "not-svg", reason: `Wikidata's flag image is a ${reference.mime} file, not an SVG`, file: reference });
    continue;
  }
  const referenceLicence = licenceOf(reference);
  const choice = CHOICES[place.code];
  if (choice === undefined) throw new Error(`${place.code} has no line in scripts/choices.data.json: run pnpm data:choose ${place.code}`);
  if (choice.source === null) {
    leftOut.push({ place, kind: "licence", reason: `Commons gives its licence as ${referenceLicence.name}, which is not public domain, CC0 or CC BY, and no MIT flag set draws the same flag at its proportions`, file: reference, licence: referenceLicence });
    continue;
  }
  chosen.push({ place, drawing: drawingOf(place, choice, reference, referenceLicence), reference, referenceLicence, item: selection.item!, choice, ...(selection.rule === "named" ? { named: selection.why } : {}) });
}

// Which place a shared drawing belongs to: a country whose English name is in the file's name, else the first
// country, else the first place. "Flag of France.svg" is France's, whoever else flies it.
const ownerByKey = new Map<string, string>();
const users = new Map<string, Place[]>();
for (const { place, drawing } of chosen) users.set(drawing.key, [...(users.get(drawing.key) ?? []), place]);
for (const [key, list] of users) {
  const countries = list.filter((user) => user.group === "country");
  const named = countries.find((user) => key.toLowerCase().includes(user.en.toLowerCase()));
  ownerByKey.set(key, (named ?? countries[0] ?? list[0]!).code);
}

const optimisedByKey = new Map<string, Optimised>();
for (const { place, drawing, reference, referenceLicence, item, choice, named } of chosen) {
  const owner = ownerByKey.get(drawing.key)!;
  let optimised = optimisedByKey.get(drawing.key);
  if (optimised === undefined) {
    optimised = optimiseFlag(drawing.text, owner, { ...(choice.precision === undefined ? {} : { precision: choice.precision }), ...(choice.keepPaths ? { keepPaths: true } : {}) });
    // The picture names its flag, so that frame() can frame it the way measured for it (FRAMINGS).
    optimised = { ...optimised, svg: optimised.svg.replace(/^<svg\b/, `<svg data-hata="${owner.toLowerCase()}"`) };
    optimisedByKey.set(drawing.key, optimised);
  }
  const bytes = Buffer.byteLength(optimised.svg);
  if (bytes > CEILING_BYTES) throw new Error(`${place.code}: ${KB(bytes)} after optimising, over the ceiling of ${KB(CEILING_BYTES)}`);
  shipped.push({ place, drawing, reference, referenceLicence, item, optimised, owner, gzip: gzipSync(optimised.svg, { level: 9 }).length, why: named === undefined ? choice.why : `Named by hand: ${named} ${choice.why}`, compared: choice.compared, designDiffers: choice.designDiffers ?? [] });
}
shipped.sort(byCode);

const owners = shipped.filter((one) => one.owner === one.place.code);

// How each picture is framed at 4:3, square and round (scripts/framing.mjs, `pnpm data:framing`), and the
// hand-adapted drawings that ship for the frames that use one.
type FramedShape = "4:3" | "1:1" | "round";
const FRAMED_SHAPES: FramedShape[] = ["4:3", "1:1", "round"];
interface Framing {
  method: "own" | "adapted" | "cover" | "crop" | "contain";
  fit: "cover" | "crop" | "contain";
  crop: { rule: "own" | "curated" | "centre" | "whole"; at: Anchor; loses?: string[] };
  source?: "flag-icons";
  file?: string;
  precision?: number;
  keepPaths?: boolean;
  coverLoses?: string[];
  refused?: string;
}
const FRAMINGS_FILE = JSON.parse(readFileSync(join(ROOT, "scripts", "framings.data.json"), "utf8")) as Record<string, Record<FramedShape, Framing>>;
const shapeName = (shape: "4:3" | "1:1"): string => shape.replace(":", "x");
interface Adapted {
  owner: string;
  shape: "4:3" | "1:1";
  module: string; // "ca.1x1"
  file: string;
  page: string;
  version: string;
  optimised: Optimised;
  raw: number;
}
const adapted: Adapted[] = [];
const unmeasuredFlags: string[] = [];
for (const one of owners) {
  const framing = FRAMINGS_FILE[one.place.code];
  if (framing === undefined || FRAMED_SHAPES.some((shape) => framing[shape] === undefined)) {
    // Not measured yet (a flag new to this build: scripts/framing.mjs reads this build's records, so it cannot measure it before). Everything is
    // written as if it were cropped from the centre, and the build stops at its end, naming what to measure.
    unmeasuredFlags.push(one.place.code);
    const placeholder: Framing = { method: "cover", fit: "cover", crop: { rule: "centre", at: "centre" } };
    FRAMINGS_FILE[one.place.code] = { "4:3": placeholder, "1:1": placeholder, round: placeholder };
    continue;
  }
  for (const shape of ["4:3", "1:1"] as const) {
    const entry = framing[shape];
    if (entry.method !== "adapted") continue;
    const candidate = setCandidates(one.place.code).find((option) => option.source === entry.source && option.file === entry.file);
    if (candidate === undefined) throw new Error(`${one.place.code}: ${entry.source} has no ${entry.file}: run pnpm data:framing ${one.place.code}`);
    const module = `${moduleName(one.place.code)}.${shapeName(shape)}`;
    const optimised = optimiseFlag(candidate.text, `${one.place.code}-${shapeName(shape)}`, { ...(entry.precision === undefined ? {} : { precision: entry.precision }), ...(entry.keepPaths ? { keepPaths: true } : {}) });
    if (Buffer.byteLength(optimised.svg) > CEILING_BYTES) throw new Error(`${module}: ${KB(Buffer.byteLength(optimised.svg))} after optimising, over the ceiling of ${KB(CEILING_BYTES)}`);
    adapted.push({ owner: one.place.code, shape, module, file: candidate.file, page: candidate.page, version: setNamed(candidate.source).version, optimised, raw: Buffer.byteLength(candidate.text) });
  }
}
const framingOf = (one: Shipped): Record<FramedShape, Framing> => FRAMINGS_FILE[one.owner]!;
const adaptedFor = (one: Shipped, shape: FramedShape): Adapted | undefined => adapted.find((entry) => entry.owner === one.owner && entry.shape === (shape === "round" ? "1:1" : shape) && framingOf(one)[shape].method === "adapted");

// 3b. Each place's other flags in real use (VARIANTS in data-config.ts): the drawing of each is fetched and licence-checked
// like any flag's, shipped as its own module (`<code>--<id>`), or as the module of the picture it shares with a flag.
interface VariantRecord {
  id: string;
  name: string;
  nameJa: string;
  status: string;
  from: string | null;
  until: string | null;
  why: string;
  source: string;
  default: boolean;
  module: string;
  frames: Record<"4:3" | "1:1" | "round", "cover" | "crop" | "contain">;
  drawing: { source: string; file: string; page: string; licence: ShippedLicence; author: string | null; credit: string | null; attributionRequired: boolean; restrictions: string[]; uploaded: string | null; width: number; height: number; bytes: number };
}
interface VariantModule {
  module: string; // "af--de-facto"
  owner: string | null; // the module whose picture it is, where a flag has the same drawing
  drawing: Drawing;
  optimised: Optimised | null;
  name: string;
  spec: string;
}
const variantSets = new Map<string, { disputed: boolean; default: string | null; variants: VariantRecord[] }>();
const variantModules: VariantModule[] = [];
const variantsLeftOut: { code: string; id: string; file: string; reason: string }[] = [];
const shippedByCode = new Map(shipped.map((one) => [one.place.code, one]));
const variantKeyFor = (code: string): string | null => (VARIANTS[code] !== undefined ? code : SAME_PLACE[code] !== undefined && VARIANTS[SAME_PLACE[code]!] !== undefined ? SAME_PLACE[code]! : null);
const commonsDrawing = (file: CommonsFile, licence: Licence): Drawing => {
  if (!licence.shipped) throw new Error(`${file.file}: licence ${licence.name} is not one that ships`);

  return {
    key: `commons:${file.file}`,
    source: "commons",
    file: file.file,
    page: file.page,
    version: null,
    licence: { kind: licence.kind, name: licence.name, url: licence.url },
    author: file.metadata.Artist ?? null,
    credit: file.metadata.Credit ?? null,
    attributionRequired: file.metadata.AttributionRequired === "true",
    templates: file.templates.map((template) => template.replace(/^Template:/, "")),
    uploaded: file.uploaded.slice(0, 10),
    bytes: file.bytes,
    text: commonsText(file),
  };
};
for (const [code, set] of Object.entries(VARIANTS)) {
  const ids = set.variants.map((variant) => variant.id);
  if (new Set(ids).size !== ids.length) throw new Error(`VARIANTS ${code}: two variants share an id`);
  if (!ids.every((id) => /^[a-z0-9]+(-[a-z0-9]+)*$/.test(id))) throw new Error(`VARIANTS ${code}: an id is not kebab case`);
  if (set.default !== null && !ids.includes(set.default)) throw new Error(`VARIANTS ${code}: default ${set.default} is not one of its variants`);
  const own = set.variants.filter((variant) => variant.file === null);
  const place = shippedByCode.get(code);
  if (set.default === null) {
    if (own.length > 0 || place !== undefined) throw new Error(`VARIANTS ${code}: no default means the place has no flag of its own, and every variant names a file`);
  } else if (place === undefined || own.length !== 1 || own[0]!.id !== set.default) throw new Error(`VARIANTS ${code}: its default must be its one variant with no file, and the place must have a flag here`);
  const records: VariantRecord[] = [];
  for (const spec of set.variants) {
    const base = { id: spec.id, name: spec.name, nameJa: spec.nameJa, status: spec.status, from: spec.from, until: spec.until, why: spec.why, source: spec.source, default: spec.id === set.default };
    if (spec.file === null) {
      const one = place!;
      const measured = FRAMINGS_FILE[one.owner]!;
      records.push({ ...base, module: moduleName(code), frames: { "4:3": measured["4:3"].fit, "1:1": measured["1:1"].fit, round: measured.round.fit }, drawing: { source: one.drawing.source, file: one.drawing.file, page: one.drawing.page, licence: one.drawing.licence, author: one.drawing.author, credit: one.drawing.credit, attributionRequired: one.drawing.attributionRequired, restrictions: restrictionsOf(one.reference.metadata), uploaded: one.drawing.uploaded, width: one.optimised.width, height: one.optimised.height, bytes: size(one) } });
      continue;
    }
    const file = commonsByFile.get(spec.file);
    if (file === undefined) throw new Error(`VARIANTS ${code} ${spec.id}: ${spec.file} is not in the Commons snapshot: run pnpm data:commons`);
    const licence = licenceOf(file);
    if (file.mime !== "image/svg+xml" || !licence.shipped) {
      variantsLeftOut.push({ code, id: spec.id, file: spec.file, reason: file.mime !== "image/svg+xml" ? `a ${file.mime} file, not an SVG` : `licence ${licence.name}` });
      continue;
    }
    const drawing = commonsDrawing(file, licence);
    const module = `${moduleName(code)}--${spec.id}`;
    const sharer = shipped.find((one) => one.drawing.key === drawing.key);
    let optimised: Optimised | null = null;
    if (sharer === undefined) {
      optimised = optimiseFlag(drawing.text, `${code}--${spec.id}`, {});
      optimised = { ...optimised, svg: optimised.svg.replace(/^<svg\b/, `<svg data-hata="${module}"`) };
      if (Buffer.byteLength(optimised.svg) > CEILING_BYTES) throw new Error(`${module}: ${KB(Buffer.byteLength(optimised.svg))} after optimising, over the ceiling of ${KB(CEILING_BYTES)}`);
    }
    const picture = sharer?.optimised ?? optimised!;
    variantModules.push({ module, owner: sharer === undefined ? null : moduleName(sharer.owner), drawing, optimised, name: spec.name, spec: `${code} ${spec.id}` });
    const measured = FRAMINGS_FILE[sharer?.owner ?? `${code}--${spec.id}`];
    const frames = measured === undefined ? ({ "4:3": "cover", "1:1": "cover", round: "cover" } as const) : ({ "4:3": measured["4:3"].fit, "1:1": measured["1:1"].fit, round: measured.round.fit } as const);
    records.push({ ...base, module, frames, drawing: { source: "commons", file: drawing.file, page: drawing.page, licence: drawing.licence, author: drawing.author, credit: drawing.credit, attributionRequired: drawing.attributionRequired, restrictions: restrictionsOf(file.metadata), uploaded: drawing.uploaded, width: picture.width, height: picture.height, bytes: Buffer.byteLength(picture.svg) } });
  }
  variantSets.set(code, { disputed: set.disputed, default: set.default, variants: records });
}
const variantsOfCode = (code: string): { disputed: boolean; default: string | null; variants: VariantRecord[] } => variantSets.get(variantKeyFor(code) ?? "") ?? { disputed: false, default: null, variants: [] };
leftOut.sort(byCode);

// 4. The source files.
const quote = (text: string): string => JSON.stringify(text);
const ratio = (width: number, height: number): string => {
  const known: [number, string][] = [[1, "1:1"], [4 / 3, "4:3"], [3 / 2, "3:2"], [5 / 3, "5:3"], [8 / 5, "8:5"], [5 / 4, "5:4"], [7 / 4, "7:4"], [13 / 7, "13:7"], [19 / 10, "19:10"], [2, "2:1"], [11 / 8, "11:8"], [7 / 5, "7:5"], [10 / 7, "10:7"], [9 / 7, "9:7"], [15 / 11, "15:11"], [18 / 11, "18:11"], [11 / 6, "11:6"], [5 / 2, "5:2"], [22 / 13, "22:13"], [28 / 37, "28:37"]];
  const value = width / height;
  const near = known.find(([target]) => Math.abs(target - value) / target < 0.002);

  return near ? near[1] : `${value.toFixed(3)}:1`;
};
const licenceWords = (licence: ShippedLicence): string => (licence.kind === "public-domain" ? "public domain" : licence.name);
const sourceWords = (drawing: Drawing): string => (drawing.source === "commons" ? `Wikimedia Commons, "${drawing.file}"` : `${drawing.source} ${drawing.version}, ${drawing.file}`);

const docOf = (one: Shipped): string => {
  const { place, optimised } = one;
  const shared = one.owner !== place.code ? ` The same picture as ${one.owner}'s.` : "";
  const name = `${place.en}${place.ja ? ` (${place.ja})` : ""}`;

  return `/**
 * The flag of ${name}, ${place.code}, as an SVG string: viewBox ${optimised.width} by ${optimised.height} (${ratio(optimised.width, optimised.height)}), ${KB(Buffer.byteLength(optimised.svg))}.${shared}
 * From ${sourceWords(one.drawing)} (${licenceWords(one.drawing.licence)}); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * \`\`\`ts
 * import flag from "@johnmorrisdotca/hata/flags/${moduleName(place.code)}";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * \`\`\`
 */`;
};

mkdirSync(FLAGS_DIR, { recursive: true });
mkdirSync(DATA_DIR, { recursive: true });
const written = new Set<string>();
for (const one of shipped) {
  const name = `${moduleName(one.place.code)}.ts`;
  written.add(name);
  const body =
    one.owner === one.place.code
      ? `${HEADER}\n// Source: ${one.drawing.page}\n\n${docOf(one)}\nconst svg: string = ${quote(one.optimised.svg)};\n\nexport { svg };\nexport default svg;\n`
      : `${HEADER}\n// Source: ${one.drawing.page}, the same drawing as ${one.owner}'s flag.\n\nimport { svg as shared } from "./${moduleName(one.owner)}";\n\n${docOf(one)}\nconst svg: string = shared;\n\nexport { svg };\nexport default svg;\n`;
  writeFileSync(join(FLAGS_DIR, name), body);
}
for (const one of adapted) {
  const name = `${one.module}.ts`;
  written.add(name);
  const place = places.find((candidate) => candidate.code === one.owner)!;
  const doc = `/**
 * The flag of ${place.en}${place.ja ? ` (${place.ja})` : ""}, ${one.owner}, drawn again by hand at ${one.shape} by flag-icons ${one.version} (MIT), as an SVG string: viewBox ${one.optimised.width} by ${one.optimised.height}, ${KB(Buffer.byteLength(one.optimised.svg))}.
 * The drawing \`flag("${one.owner}", { shape: "${one.shape}" })\` uses${one.shape === "1:1" ? " (and the round frame, in a circle)" : ""}, made for that shape by hand rather than cut from the flag. The /manifest entry's \`framings\` say how each frame was chosen.
 *
 * @example
 * \`\`\`ts
 * import square from "@johnmorrisdotca/hata/flags/${one.module}";
 *
 * element.innerHTML = square;
 * \`\`\`
 */`;
  writeFileSync(join(FLAGS_DIR, name), `${HEADER}\n// Source: ${one.page}\n\n${doc}\nconst svg: string = ${quote(one.optimised.svg)};\n\nexport { svg };\nexport default svg;\n`);
}
for (const one of variantModules) {
  const name = `${one.module}.ts`;
  written.add(name);
  const [code, id] = one.spec.split(" ") as [string, string];
  const place = places.find((candidate) => candidate.code === code)!;
  const picture = one.optimised ?? shipped.find((candidate) => moduleName(candidate.owner) === one.owner)!.optimised;
  const doc = `/**
 * ${one.name}: one of the flags of ${place.en}${place.ja ? ` (${place.ja})` : ""}, ${code}, in real use, as an SVG string: viewBox ${picture.width} by ${picture.height} (${ratio(picture.width, picture.height)}), ${KB(Buffer.byteLength(picture.svg))}.${one.owner === null ? "" : ` The same picture as ${one.owner.toUpperCase()}'s.`}
 * From ${sourceWords(one.drawing)} (${licenceWords(one.drawing.licence)}). \`flag("${code}", { variant: "${id}" })\` loads it, and \`variantsOf("${code}")\` says its status, dates and why it is offered.
 *
 * @example
 * \`\`\`ts
 * import flag from "@johnmorrisdotca/hata/flags/${one.module}";
 *
 * element.innerHTML = flag;
 * \`\`\`
 */`;
  const body =
    one.owner === null
      ? `${HEADER}\n// Source: ${one.drawing.page}\n\n${doc}\nconst svg: string = ${quote(one.optimised!.svg)};\n\nexport { svg };\nexport default svg;\n`
      : `${HEADER}\n// Source: ${one.drawing.page}, the same drawing as ${one.owner.toUpperCase()}'s flag.\n\nimport { svg as shared } from "./${one.owner}";\n\n${doc}\nconst svg: string = shared;\n\nexport { svg };\nexport default svg;\n`;
  writeFileSync(join(FLAGS_DIR, name), body);
}
for (const old of readdirSync(FLAGS_DIR)) if (!written.has(old)) rmSync(join(FLAGS_DIR, old));

const codes = shipped.map((one) => one.place.code);
const columns = (list: string[], per: number): string => {
  const lines: string[] = [];
  for (let at = 0; at < list.length; at += per) lines.push(`  ${list.slice(at, at + per).map(quote).join(", ")},`);
  return lines.join("\n");
};
writeFileSync(
  join(DATA_DIR, "codes.data.ts"),
  `${HEADER}
// The ${codes.length} codes with a flag: ISO 3166-1 alpha-2 for a country, ISO 3166-2 for a subdivision, as Kuni writes them.

/**
 * Every code with a flag in this version, in order: the countries by ISO 3166-1 alpha-2 code ("AD" to "ZW", and
 * "XK" for Kosovo), then the first-level subdivisions of ${SUBDIVISION_COUNTRIES.length} countries by ISO 3166-2 code ("AT-1", "AU-NSW",
 * "CA-AB", "DE-BY", "JP-01", "US-AK"). A place Kuni knows and this list leaves out is in /manifest's \`LEFT_OUT\`
 * with the reason.
 *
 * @example
 * \`\`\`ts
 * import { FLAG_CODES } from "@johnmorrisdotca/hata";
 *
 * FLAG_CODES.length;                                  // ${codes.length}
 * FLAG_CODES.filter((code) => code.startsWith("JP-")); // the ${shipped.filter((one) => one.place.group === "jp").length} prefectures with a flag
 * \`\`\`
 */
const FLAG_CODES = [
${columns(codes, 12)}
] as const;

/**
 * A code with a flag, as Kuni writes it: "JP", "JP-13", "CA-ON", "US-TX".
 *
 * @example
 * \`\`\`ts
 * import { flagCode, type FlagCode } from "@johnmorrisdotca/hata";
 *
 * const home: FlagCode | null = flagCode("jp-13"); // "JP-13"
 * \`\`\`
 */
type FlagCode = (typeof FLAG_CODES)[number];

export { FLAG_CODES };
export type { FlagCode };
`,
);

const variantLoaderLines = [...new Set([...codes, ...places.map((place) => place.code).filter((code) => variantKeyFor(code) !== null)])]
  .filter((code) => variantsOfCode(code).variants.length > 0)
  .sort()
  .flatMap((code) => variantsOfCode(code).variants.map((variant) => `  ${quote(`${code}--${variant.id}`)}: () => import("../flags/${variant.module}.js"),`));
writeFileSync(
  join(DATA_DIR, "loaders.data.ts"),
  `${HEADER}
// One dynamic import for each of the ${codes.length} flags, so a bundler makes a chunk of each and a page downloads only the flags it shows.

type Loader = () => Promise<{ svg: string }>;

const LOADERS: Readonly<Record<string, Loader>> = {
${codes.map((code) => `  ${quote(code)}: () => import("../flags/${moduleName(code)}.js"),`).join("\n")}
};

export { LOADERS };
`,
);

writeFileSync(
  join(DATA_DIR, "variants.data.ts"),
  `${HEADER}
// Every variant of every code with one, by "<code>--<id>" (the default's included, and a code that is the same place as
// another with that place's variants), so \`flag(code, { variant })\` is one lookup. Its own entry (dist/variants.js),
// loaded only when a variant is asked for, so /load stays small.

type Loader = () => Promise<{ svg: string }>;

const VARIANT_LOADERS: Readonly<Record<string, Loader>> = {
${variantLoaderLines.join("\n")}
};

export { VARIANT_LOADERS };
`,
);

writeFileSync(
  join(DATA_DIR, "adapted.data.ts"),
  `${HEADER}
// The drawings made by hand for a frame that /load uses, by code and shape ("CA 1:1"; "CA round" is the square in a
// circle). Its own entry (dist/adapted.js), loaded only when a frame is asked for, so /load stays small.

type Loader = () => Promise<{ svg: string }>;

const ADAPTED: Readonly<Record<string, Loader>> = {
${shipped.flatMap((one) => FRAMED_SHAPES.flatMap((shape) => { const found = adaptedFor(one, shape); return found === undefined ? [] : [`  ${quote(`${one.place.code} ${shape}`)}: () => import("../flags/${found.module}.js"),`]; })).join("\n")}
};

export { ADAPTED };
`,
);

// Every flag's names in English and Japanese (Kuni's) and its aspect ratio, for /names and <hata-flag>: a name to
// read aloud, and the box to keep before the picture arrives.
writeFileSync(
  join(DATA_DIR, "names.data.ts"),
  `${HEADER}
// From Kuni ${JSON.parse(readFileSync(join(ROOT, "node_modules", "@johnmorrisdotca", "kuni", "package.json"), "utf8")).version}: each flag's place in English and Japanese, and the flag's width over its height.

const NAMES: Readonly<Record<string, readonly [en: string, ja: string, aspect: number]>> = {
${shipped.map((one) => `  ${quote(one.place.code)}: [${quote(one.place.en)}, ${quote(one.place.ja ?? one.place.en)}, ${Number((one.optimised.width / one.optimised.height).toFixed(4))}],`).join("\n")}
${places.filter((place) => shippedByCode.get(place.code) === undefined && variantsOfCode(place.code).variants.length > 0).map((place) => `  ${quote(place.code)}: [${quote(place.en)}, ${quote(place.ja ?? place.en)}, ${Number((variantsOfCode(place.code).variants[0]!.drawing.width / variantsOfCode(place.code).variants[0]!.drawing.height).toFixed(4))}],`).join("\n")}
};

export { NAMES };
`,
);

// What frame() does with each picture at 4:3, square and round, where it is not a crop from the centre: a letter for
// each (c cover, a a crop kept at the side CROPS names, w the whole flag), keyed by the name the picture carries
// (data-hata). CROPS is every picture's side for `fit: "crop"` asked for by name, wherever it is not the centre.
const LETTER: Record<Framing["fit"], string> = { cover: "c", crop: "a", contain: "w" };
const cropRows = owners
  .map((one) => [moduleName(one.place.code), FOCUS[one.place.code]?.at] as const)
  .filter((row): row is readonly [string, "left" | "right" | "top" | "bottom"] => row[1] !== undefined && row[1] !== "whole");
// A variant with a picture of its own is framed like any flag (scripts/framing.mjs measures it under "<code>--<id>").
const variantPictures = variantModules.filter((one) => one.optimised !== null).map((one) => ({ module: one.module, key: one.spec.replace(" ", "--"), optimised: one.optimised! }));
const unmeasured = variantPictures.filter((one) => FRAMINGS_FILE[one.key] === undefined);
const framingRows = [
  ...owners.map((one) => [moduleName(one.place.code), FRAMED_SHAPES.map((shape) => LETTER[framingOf(one)[shape].fit]).join(",")] as const),
  ...variantPictures.filter((one) => FRAMINGS_FILE[one.key] !== undefined).map((one) => [one.module, FRAMED_SHAPES.map((shape) => LETTER[FRAMINGS_FILE[one.key]![shape].fit]).join(",")] as const),
].filter(([, letters]) => letters !== "c,c,c");
// Written as lists of names under the value they share, so that the tables stay small in the main entry.
const grouped = (rows: readonly (readonly [string, string])[]): string => {
  const byValue = new Map<string, string[]>();
  for (const [name, value] of rows) byValue.set(value, [...(byValue.get(value) ?? []), name]);

  return [...byValue].map(([value, names]) => `  ${quote(value)}: ${quote(names.join(" "))},`).join("\n");
};
writeFileSync(
  join(DATA_DIR, "framings.data.ts"),
  `${HEADER}
// How frame() fits each flag at 4:3, square and round by default, where a crop from the centre would lose a colour:
// c a crop from the centre, a a crop kept at the side CROPS names, w the whole flag. Measured by pnpm data:framing.
// Each row is the three letters and the names of the flags that share them.
const PACKED: Readonly<Record<string, string>> = {
${grouped(framingRows)}
};

// The side a crop of each flag keeps where it is not the centre, judged by hand (FOCUS in scripts/data-config.ts):
// what \`fit: "crop"\` asked for by name does, and \`fit: "auto"\` where FRAMINGS says "a". Each row is a side and the
// names of the flags that keep it.
const SIDES: Readonly<Record<string, string>> = {
${grouped(cropRows)}
};

const unpack = <Value extends string>(rows: Readonly<Record<string, string>>): Readonly<Record<string, Value>> =>
  Object.fromEntries(Object.entries(rows).flatMap(([value, names]) => names.split(" ").map((name) => [name, value as Value])));

const FRAMINGS: Readonly<Record<string, string>> = unpack(PACKED);
const CROPS: Readonly<Record<string, "left" | "right" | "top" | "bottom">> = unpack(SIDES);

export { CROPS, FRAMINGS };
`,
);

// The crop a record gives for one frame: which crop `fit: "auto"` does (own, curated, centre, or none because the flag is
// shown whole), the side `fit: "crop"` keeps, why a person chose it, and the colours it drops.
const cropOf = (one: Shipped, framing: Framing): { rule: string; at: Anchor; why: string | null; loses: string[] } => {
  const { rule, at, loses } = framing.crop;
  const focus = FOCUS[one.owner];
  const why = rule === "own" || focus === undefined ? null : `${focus.why}${rule === "curated" && focus.loses !== undefined ? ` ${focus.loses}` : ""}`;

  return { rule, at, why, loses: loses ?? (rule === "whole" && focus === undefined ? framing.coverLoses ?? [] : []) };
};

// The manifest: one row a flag, and one a code left out.
const row = (one: Shipped): string => {
  const { drawing, reference } = one;
  const record = {
    code: one.place.code,
    source: drawing.source,
    file: drawing.file,
    page: drawing.page,
    version: drawing.version,
    wikidata: one.item,
    licence: drawing.licence,
    author: drawing.author,
    credit: drawing.credit,
    attributionRequired: drawing.attributionRequired,
    restrictions: restrictionsOf(reference.metadata),
    templates: drawing.templates,
    uploaded: drawing.uploaded,
    fetched: commons.read,
    reference: drawing.source === "commons" ? null : { file: reference.file, page: reference.page, licence: one.referenceLicence.name },
    why: one.why,
    sameAs: one.owner === one.place.code ? null : one.owner,
    width: one.optimised.width,
    height: one.optimised.height,
    bytes: size(one),
    gzip: one.gzip,
    notes: one.optimised.notes,
    disputed: variantsOfCode(one.place.code).disputed,
    defaultVariant: variantsOfCode(one.place.code).default,
    variants: variantsOfCode(one.place.code).variants,
    framings: Object.fromEntries(
      FRAMED_SHAPES.map((shape) => {
        const framing = framingOf(one)[shape];
        const found = adaptedFor(one, shape);
        return [
          shape,
          {
            method: framing.method,
            fit: framing.fit,
            source: found === undefined ? null : "flag-icons",
            file: found?.file ?? null,
            page: found?.page ?? null,
            bytes: found === undefined ? null : Buffer.byteLength(found.optimised.svg),
            coverLoses: framing.coverLoses ?? [],
            crop: cropOf(one, framing),
          },
        ];
      }),
    ),
  };
  return `  ${JSON.stringify(record)},`;
};
writeFileSync(
  join(DATA_DIR, "manifest.data.ts"),
  `${HEADER}
// Where each flag comes from, under what licence, and why that drawing was chosen; and the codes left out with why.
// Sources: Wikidata (CC0), the flag image (P41) of each place, read ${wikidata.read}; Wikimedia Commons, each file's page,
// read ${commons.read}; flag-icons ${setNamed("flag-icons").version}, country-flag-icons ${setNamed("country-flag-icons").version} and circle-flags ${setNamed("circle-flags").version} (MIT), compared by pnpm data:choose.

import type { FlagRecord, LeftOutRecord } from "../manifest.types";

// The pictures that only a variant has, for scripts/framing.mjs to measure: "<code>--<id>" and the picture's box.
const VARIANT_PICTURES: readonly { code: string; width: number; height: number }[] = [
${variantPictures.map((one) => `  ${JSON.stringify({ code: one.key, width: one.optimised.width, height: one.optimised.height })},`).join("\n")}
];

const RECORDS: readonly FlagRecord[] = [
${shipped.map(row).join("\n")}
];

const LEFT_OUT: readonly LeftOutRecord[] = [
${leftOut.map((one) => `  ${JSON.stringify({ code: one.place.code, kind: one.kind, reason: one.reason, file: one.file?.file ?? null, page: one.file?.page ?? null, licence: one.licence?.name ?? null, disputed: variantsOfCode(one.place.code).disputed, defaultVariant: variantsOfCode(one.place.code).default, variants: variantsOfCode(one.place.code).variants })},`).join("\n")}
];

export { LEFT_OUT, RECORDS, VARIANT_PICTURES };
`,
);

// 5. The documents that list the flags.
const groupName: Record<Group, string> = {
  country: "Countries",
  jp: "Japan's prefectures",
  ca: "Canada's provinces and territories",
  us: "The United States' states, district and outlying areas",
  au: "Australia's states and territories",
  gb: "The United Kingdom's four countries",
  de: "Germany's states",
  fr: "France's regions and overseas collectivities",
  ch: "Switzerland's cantons",
  at: "Austria's states",
  br: "Brazil's states and Federal District",
};
const groups: Group[] = ["country", ...SUBDIVISION_COUNTRIES.map((code) => code.toLowerCase())];
for (const group of groups) if (groupName[group] === undefined) throw new Error(`no heading for ${group} in build-data.ts's groupName`);
const cell = (text: string | null | undefined): string => String(text ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const linkTo = (file: string, page: string): string => `[${cell(file)}](${page})`;
const count = (group: Group): { total: number; flags: number } => ({ total: places.filter((place) => place.group === group).length, flags: shipped.filter((one) => one.place.group === group).length });
const tally = (list: Shipped[], key: (one: Shipped) => string): Record<string, number> => {
  const out: Record<string, number> = {};
  for (const one of list) out[key(one)] = (out[key(one)] ?? 0) + 1;
  return Object.fromEntries(Object.entries(out).sort((a, b) => b[1] - a[1]));
};

const provenance = `# Every flag: where it comes from, its licence, and why that drawing

Made by \`pnpm data\` from the Wikidata snapshot of ${wikidata.read}, the Commons snapshot of ${commons.read} and the choices
\`pnpm data:choose\` made; a test fails if this list and the data differ. Each drawing's licence is its own: a
Commons file's is the one Commons states on its page, linked here, and a flag set's is the set's MIT licence.
Authors are as Commons gives them. Commons notes on most flags that the use of an insignia may be restricted by
law, apart from copyright; see NOTICE.md.

Which drawing won, of ${shipped.length} flags: ${Object.entries(tally(shipped, (one) => one.drawing.source)).map(([source, number]) => `${source} ${number}`).join(", ")}. How the choice is
made is in \`scripts/choose.mjs\`; the reason for each flag is in its row.

${groups
  .map((group) => {
    const { total, flags } = count(group);
    return `## ${groupName[group]}: ${flags} of ${total}

| Code | Place | Drawing | Licence | Author | Size | Why this drawing |
| --- | --- | --- | --- | --- | --- | --- |
${shipped
  .filter((one) => one.place.group === group)
  .map((one) => `| \`${one.place.code}\` | ${cell(one.place.en)}${one.place.ja ? ` (${cell(one.place.ja)})` : ""} | ${one.drawing.source === "commons" ? "" : `${one.drawing.source}: `}${linkTo(one.drawing.file, one.drawing.page)}${one.owner !== one.place.code ? `, as ${one.owner}` : ""} | ${cell(licenceWords(one.drawing.licence))} | ${cell(one.drawing.author ?? "not stated")} | ${KB(size(one))} | ${cell(one.why)} |`)
  .join("\n")}`;
  })
  .join("\n\n")}
`;
writeFileSync(join(ROOT, "docs", "provenance.md"), provenance);

const lookAt = shipped.filter((one) => one.designDiffers.length > 0);
const unreviewed = lookAt.filter((one) => REVIEWED[one.place.code] === undefined).map((one) => one.place.code);
const leftOutDoc = `# The codes with no flag in this version, and why

Made by \`pnpm data\`; a test fails if this list and the data differ. Every code Kuni knows (${places.length}: the
${places.filter((place) => place.group === "country").length} countries and the first level of ${SUBDIVISION_COUNTRIES.join(", ")}) either has a flag or is here with its reason.
The decisions behind the reasons are in [decisions.md](decisions.md).

${
  leftOut.length === 0
    ? "None."
    : `| Code | Place | Why | Commons file |
| --- | --- | --- | --- |
${leftOut.map((one) => `| \`${one.place.code}\` | ${cell(one.place.en)} | ${cell(one.reason)} | ${one.file ? linkTo(one.file.file, one.file.page) : ""} |`).join("\n")}`
}

## Left out for their licence, for the maintainer to decide

${(() => {
  const list = leftOut.filter((one) => one.kind === "licence");
  if (list.length === 0) return "None: every flag Wikidata names is public domain, CC0 or CC BY on Commons, or drawn the same by an MIT set.";
  return `These files are on Commons under a licence that is not public domain, CC0 or CC BY, and no MIT flag set draws the
same flag at its true proportions, so they are not bundled. Each could come in by a decision, recorded in
\`ACCEPTED\` in \`scripts/data-config.ts\`: accepting the licence as it is (CC BY-SA would bind every user of the
package to share alike), or naming a public-domain drawing of the same flag on Commons.

| Code | Place | Commons file | Licence as Commons states it | A public-domain template on the page too |
| --- | --- | --- | --- | --- |
${list.map((one) => `| \`${one.place.code}\` | ${cell(one.place.en)} | ${linkTo(one.file!.file, one.file!.page)} | ${cell(one.licence?.name)} | ${one.licence && !one.licence.shipped && one.licence.publicDomainTemplate ? "yes" : "no"} |`).join("\n")}`;
})()}
`;
writeFileSync(join(ROOT, "docs", "left-out.md"), leftOutDoc);

const comparedDoc = `# Where the flag sets draw something else

Made by \`pnpm data\` from \`scripts/choices.data.json\` and \`REVIEWED\` in \`scripts/data-config.ts\`; a test fails if
this list and the data differ, or a place on it has not been looked at. \`pnpm data:choose\` compares every set's
drawing of a flag, at whatever shape the set draws it (4:3, 3:2, 1:1 or round), with Commons' drawing put in the
same shape, cropped or stretched, at 96 pixels wide and by the names of the colours, so that fine detail and a
shade do not count. A set whose closest drawing still differs in more than a quarter of its pixels is listed
here, and a person has looked at the drawings side by side (\`pnpm data:sheet <out.png> --compared\`). Where the
difference is the design itself, [decisions.md](decisions.md) says which ships and why.

| Code | Place | Shipped | Sets that differ (closest drawing, share of pixels) | Looked at |
| --- | --- | --- | --- | --- |
${lookAt.map((one) => `| \`${one.place.code}\` | ${cell(one.place.en)} | ${one.drawing.source} | ${one.designDiffers.map((source) => `${source} ${Math.round(Math.min(...Object.entries(one.compared).filter(([label]) => label.startsWith(`${source} `)).map(([, entry]) => entry.design)) * 100)}%`).join(", ")} | ${cell(REVIEWED[one.place.code] ?? "not yet")} |`).join("\n")}
`;
writeFileSync(join(ROOT, "docs", "compared.md"), comparedDoc);

// Every flag a person judged where a crop should sit, with the reason, and every flag shown whole by default only because
// the measure says a crop loses a colour: docs/framing.md.
const SIDE_WORDS: Record<string, string> = { left: "kept at the hoist (left)", right: "kept at the fly (right)", top: "kept at the top", bottom: "kept at the bottom" };
const curated = owners.filter((one) => FOCUS[one.place.code] !== undefined);
const measuredWhole = owners.filter((one) => FOCUS[one.place.code] === undefined && FRAMED_SHAPES.some((shape) => framingOf(one)[shape].crop.rule === "whole"));
const framingDoc = `# How a crop of each flag is chosen

Made by \`pnpm data\`; a test fails if this list and the data differ. Every flag is offered both whole
(\`fit: "whole"\`: all of the flag, with clear bands, on a neutral disc when round) and cropped (\`fit: "crop"\`), at 4:3,
square and round. \`fit: "auto"\`, the default, picks the crop where one shows the flag fairly, and the whole flag where not.

What the crop is, in the order \`auto\` tries:

1. **The flag is that shape already**: nothing to crop.
2. **\`flag(code, { shape })\`, not \`frame()\`: the drawing flag-icons made by hand for the shape**, where it keeps the flag's
   colours and flag-icons does not draw another design. A person drew it for the shape, so it is a good crop; \`frame()\` works
   on one SVG and cannot use it, so for \`frame()\` the rows below are what a crop is.
3. **A crop kept at the side a person chose** (the table below). A flag whose meaning is in a canton or at the hoist (the United
   States' stars and stripes, Uruguay's Sun of May, the Bahamas' triangle) is cropped there, so that the emblem and a slice of
   the body show; a flag whose meaning is at the fly (Rwanda's sun) is cropped there. The crop must keep every colour that covers
   5% of the flag at no less than half its share, unless the reason beside the flag says why a colour may shrink.
4. **A crop from the centre** where nobody chose a side and the crop keeps the colours: Japan's disc, a coat of arms, a tricolour.
5. **The whole flag** where no crop keeps it true.

A crop asked for by name (\`fit: "crop"\`) always crops, at the chosen side, and from the centre where there is none: it is
yours to ask for even where the default is the whole flag. The side of every flag is in \`manifest(code).framings[shape].crop\`.

Judged on 2026-10-09 by looking at every flag's whole picture beside its centre crop, and again at the chosen crop beside the whole flag.

## Flags with a side chosen by hand (${curated.length})

"Default" is what \`frame()\` does with \`auto\` at the square: the crop at the side, or the whole flag where the measure says the crop loses a colour
no reason excuses, or where a person judged that no crop shows the flag.

| Code | Place | Crop | Default of \`frame()\` at the square | Why |
| --- | --- | --- | --- | --- |
${curated
  .map((one) => {
    const focus = FOCUS[one.place.code]!;
    const crop = framingOf(one)["1:1"].crop;
    const how = focus.at === "whole" ? "centre, on request only" : SIDE_WORDS[focus.at]!;
    const fallback = crop.rule === "curated" ? (crop.loses !== undefined && crop.loses.length > 0 ? "the crop, a colour shrunk (see why)" : "the crop") : crop.rule === "own" ? "its own shape" : "the whole flag";
    return `| \`${one.place.code}\` | ${cell(one.place.en)} | ${how} | ${fallback} | ${cell(`${focus.why}${focus.loses === undefined ? "" : ` ${focus.loses}`}`)} |`;
  })
  .join("\n")}

## Flags shown whole by default because a crop loses a colour (${measuredWhole.length})

Nobody chose a side for these, and the measure found that a centre crop drops a colour covering 5% of the flag.

| Code | Place | The centre crop at the square loses |
| --- | --- | --- |
${measuredWhole.map((one) => `| \`${one.place.code}\` | ${cell(one.place.en)} | ${cell(framingOf(one)["1:1"].coverLoses?.join(", ") || framingOf(one).round.coverLoses?.join(", ") || framingOf(one)["4:3"].coverLoses?.join(", "))} |`).join("\n")}
`;
writeFileSync(join(ROOT, "docs", "framing.md"), framingDoc);

// Every place with more than one flag in real use: docs/variants.md.
const variantsDoc = `# Disputed and alternative flags

Made by \`pnpm data\`; a test fails if this list and the data differ. A place with more than one flag in real use has them
all here, each with its status, its dates, the reason it is offered and a source, and one of them is the default
(\`flag(code)\`), except where the place has no flag of its own (Northern Ireland). Hata takes no side: the status says what
authority a flag has, and the default is the flag of the authority the world recognises, or the place's own flag where it has one.
The decisions behind the defaults are in [decisions.md](decisions.md).

\`flag(code, { variant: id })\` loads one; \`variantsOf(code)\` from \`/manifest\` lists them; \`<hata-flag code variant>\` draws one; each is its
own module, \`/flags/<code>--<id>\`, and file, \`svg/<code>--<id>.svg\`.

| Code | Place | Id | Status | Dates | Default | Why | Source | Drawing | Licence |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${[...variantSets]
  .flatMap(([code, set]) => {
    const place = places.find((candidate) => candidate.code === code)!;
    return set.variants.map((variant) => `| \`${code}\`${set.disputed ? " (disputed)" : ""} | ${cell(place.en)} | \`${variant.id}\` | ${variant.status} | ${cell([variant.from, variant.until].filter((one) => one !== null).join(" to ") || "")} | ${variant.default ? "yes" : ""} | ${cell(variant.why)} | [source](${variant.source}) | ${linkTo(variant.drawing.file, variant.drawing.page)} | ${cell(variant.drawing.licence.name)} |`);
  })
  .join("\n")}

## Offered in the data and left out

${variantsLeftOut.length === 0 ? "None: every drawing named in VARIANTS ships." : variantsLeftOut.map((one) => `- \`${one.code}\` \`${one.id}\`: ${cell(one.file)}, ${one.reason}.`).join("\n")}
`;
writeFileSync(join(ROOT, "docs", "variants.md"), variantsDoc);

const totals = { bytes: owners.reduce((sum, one) => sum + size(one), 0), gzip: owners.reduce((sum, one) => sum + one.gzip, 0), raw: owners.reduce((sum, one) => sum + one.drawing.bytes, 0) };
const sizes = owners.map(size).sort((a, b) => a - b);
const median = sizes[Math.floor(sizes.length / 2)] ?? 0;
const over = owners.filter((one) => size(one) > BUDGET_BYTES).sort((a, b) => size(b) - size(a));

const sizesDoc = `# Sizes

Made by \`pnpm data\`; a test fails if this list and the data differ. Sizes are of the optimised SVG as shipped
(\`dist/svg/<code>.svg\`, and the string in \`/flags/<code>\`), and gzipped at level 9 as a server would send it.

| | Pictures | SVG | Gzipped |
| --- | --- | --- | --- |
| Every flag | ${owners.length} (${shipped.length} codes; ${shipped.length - owners.length} share another's picture) | ${KB(totals.bytes)} | ${KB(totals.gzip)} |
| The same drawings as their sources have them | ${owners.length} | ${KB(totals.raw)} | |
| The median flag | | ${KB(median)} | |
| The countries alone | ${owners.filter((one) => one.place.group === "country").length} | ${KB(owners.filter((one) => one.place.group === "country").reduce((sum, one) => sum + size(one), 0))} | ${KB(owners.filter((one) => one.place.group === "country").reduce((sum, one) => sum + one.gzip, 0))} |
| Drawings made for a frame (flag-icons' 4:3 and square, \`/flags/<code>.4x3\`, \`.1x1\`) | ${adapted.length} | ${KB(adapted.reduce((sum, one) => sum + Buffer.byteLength(one.optimised.svg), 0))} | ${KB(adapted.reduce((sum, one) => sum + gzipSync(one.optimised.svg, { level: 9 }).length, 0))} |

## Over the budget

The budget is ${KB(BUDGET_BYTES)} a flag; a flag may not be larger than ${KB(CEILING_BYTES)}, or the build stops.
The flags over the budget carry a detailed coat of arms or seal, drawn as it is in their source; they are shipped,
and listed here so a new one is noticed (the size test holds this list).

${
  over.length === 0
    ? "None."
    : `| Code | Place | SVG | Gzipped | As its source has it |
| --- | --- | --- | --- | --- |
${over.map((one) => `| \`${one.place.code}\` | ${cell(one.place.en)} | ${KB(size(one))} | ${KB(one.gzip)} | ${KB(one.drawing.bytes)} |`).join("\n")}`
}

## Drawings made for a frame over the budget

${(() => {
  const heavy = adapted.filter((one) => Buffer.byteLength(one.optimised.svg) > BUDGET_BYTES).sort((a, b) => Buffer.byteLength(b.optimised.svg) - Buffer.byteLength(a.optimised.svg));
  if (heavy.length === 0) return "None.";
  return `They carry the same coats of arms as the flags, drawn again by flag-icons; a page loads one only when it asks for that frame.

| Module | Place | SVG | Gzipped | As flag-icons has it |
| --- | --- | --- | --- | --- |
${heavy.map((one) => `| \`${one.module}\` | ${cell(places.find((place) => place.code === one.owner)!.en)} | ${KB(Buffer.byteLength(one.optimised.svg))} | ${KB(gzipSync(one.optimised.svg, { level: 9 }).length)} | ${KB(one.raw)} |`).join("\n")}`;
})()}

## Worth knowing about some pictures

${(() => {
  const noted = owners.filter((one) => one.optimised.notes.length > 0);
  if (noted.length === 0) return "Nothing: no flag draws text with a font or embeds a raster picture.";
  return noted.map((one) => `- \`${one.place.code}\` ${cell(one.place.en)}: ${one.optimised.notes.join("; ")}.`).join("\n");
})()}
`;
writeFileSync(join(ROOT, "docs", "sizes.md"), sizesDoc);

// The credits in NOTICE.md, between its markers: every Commons drawing whose licence asks for credit, and every
// flag set a drawing was taken from, with the flags it gave and its licence in full, as MIT asks.
const notice = readFileSync(join(ROOT, "NOTICE.md"), "utf8");
const between = (text: string, name: string, body: string): string => {
  const start = `<!-- ${name}:start -->`;
  const end = `<!-- ${name}:end -->`;
  if (!text.includes(start) || !text.includes(end)) throw new Error(`NOTICE.md has no ${name} markers`);
  return `${text.slice(0, text.indexOf(start))}${start}\n${body}\n${end}${text.slice(text.indexOf(end) + end.length)}`;
};
const credited = owners.filter((one) => one.drawing.source === "commons" && (one.drawing.licence.kind === "cc-by" || one.drawing.licence.kind === "accepted" || one.drawing.attributionRequired));
const creditOf = (one: Shipped): string => {
  const metadata = one.reference.metadata;
  const by = [metadata.Attribution ? `attributed as "${metadata.Attribution}"` : null, metadata.Artist ? `author as Commons gives it: ${metadata.Artist}` : null].filter(Boolean).join("; ");
  return `- \`${one.place.code}\` ${one.place.en}: "${one.drawing.file}", ${by || "no author named on Commons"}; ${one.drawing.licence.name}${one.drawing.licence.url ? ` (${one.drawing.licence.url})` : ""}; ${one.drawing.page}`;
};
const setsUsed = [...new Set([...owners.filter((one) => one.drawing.source !== "commons").map((one) => one.drawing.source), ...(adapted.length > 0 ? ["flag-icons"] : [])])].sort();
const setsBody =
  setsUsed.length === 0
    ? "No drawing in this version is taken from a flag set."
    : setsUsed
        .map((name) => {
          const set = setNamed(name);
          const flags = shipped.filter((one) => one.drawing.source === name).map((one) => `\`${one.place.code}\``);
          const framed = name === "flag-icons" ? adapted.map((one) => `\`${one.module}\``) : [];
          const licence = readFileSync(join(ROOT, "node_modules", name, "LICENSE"), "utf8").replace(/^# /, "").trim();
          return `### ${name} ${set.version}\n\n${set.home}, on npm as \`${name}\`. ${[flags.length > 0 ? `The drawings of ${flags.join(", ")}.` : "", framed.length > 0 ? `The drawings made for a frame: ${framed.join(", ")}.` : ""].filter(Boolean).join(" ")}\n\n\`\`\`text\n${licence}\n\`\`\``;
        })
        .join("\n\n");
const variantCredits = [...variantSets]
  .flatMap(([code, set]) => set.variants.filter((variant) => !variant.default && (variant.drawing.licence.kind === "cc-by" || variant.drawing.licence.kind === "accepted" || variant.drawing.attributionRequired)).map((variant) => ({ code, variant })))
  .filter(({ variant }) => !credited.some((one) => one.drawing.file === variant.drawing.file))
  .map(({ code, variant }) => `- \`${code}--${variant.id}\` ${places.find((place) => place.code === code)!.en}, ${variant.name}: "${variant.drawing.file}", ${variant.drawing.author ? `author as Commons gives it: ${variant.drawing.author}` : "no author named on Commons"}; ${variant.drawing.licence.name}${variant.drawing.licence.url ? ` (${variant.drawing.licence.url})` : ""}; ${variant.drawing.page}`);
writeFileSync(join(ROOT, "NOTICE.md"), between(between(notice, "attributions", [...credited.map(creditOf), ...variantCredits].length === 0 ? "No Commons drawing in this version is under a licence that asks for credit." : [...credited.map(creditOf), ...variantCredits].join("\n")), "sets", setsBody));

// 6. What happened.
console.log(`variants: ${[...variantSets].map(([code, set]) => `${code} ${set.variants.length}`).join(", ")}${variantsLeftOut.length > 0 ? `; left out: ${variantsLeftOut.map((one) => `${one.code} ${one.id} (${one.reason})`).join(", ")}` : ""}`);
const summary = groups.map((group) => `${group} ${count(group).flags}/${count(group).total}`).join(", ");
console.log(`${shipped.length} flags (${owners.length} pictures): ${summary}`);
console.log(`winners: ${JSON.stringify(tally(shipped, (one) => one.drawing.source))}`);
console.log(`${KB(totals.bytes)} of SVG, ${KB(totals.gzip)} gzipped; ${KB(totals.raw)} as their sources have them`);
console.log(`licences: ${JSON.stringify(tally(shipped, (one) => one.drawing.licence.name))}`);
console.log(`left out: ${leftOut.map((one) => `${one.place.code} (${one.kind})`).join(", ") || "none"}`);
console.log(`over the ${KB(BUDGET_BYTES)} budget: ${over.length} flags`);
console.log(`where a set draws something else: ${lookAt.length} flags${unreviewed.length > 0 ? `, not yet looked at: ${unreviewed.join(" ")}` : ", every one looked at"}`);
if (report) for (const one of shipped) console.log(`${one.place.code.padEnd(6)} ${KB(size(one)).padStart(9)} ${one.drawing.source.padEnd(19)} ${one.drawing.licence.name.padEnd(16)} ${one.drawing.file}`);
const toMeasure = [...unmeasuredFlags, ...unmeasured.map((one) => one.key)];
if (toMeasure.length > 0) throw new Error(`${toMeasure.join(", ")} have no line in scripts/framings.data.json, so everything is written as cropped from the centre: run pnpm data:framing ${toMeasure.join(" ")}, then pnpm data again`);
