// The demo page's own words, in the two languages it speaks. A `{name}` in a line is filled in when it is shown.
// docs/strings-ja.md lists these beside each other, and a test keeps that list true (`pnpm docs:make` rewrites it).
export const WORDS = {
  en: {
    pageApi: "API reference",
    pitch: "Flags as SVG for every country, and the regions of Japan, Canada, the United States, Australia, the United Kingdom, Germany, France, Switzerland, Austria and Brazil, at their true proportions, keyed by ISO 3166 code. Tap a flag for where it comes from, its licence, the code to embed it and downloads; or play the quiz.",
    name: "Hata (旗) is Japanese for “flag”.",
    nameLink: "About the name",
    foot: "Every flag is drawn from the package's own files in your browser. Nothing leaves this page.",
    moreTitle: "Using it",
    moreText: "Each flag is a module of its own, so a page carries only the flags it imports; the lookup loads one by its code when it is wanted. Each line below is all it takes.",
    tab_gallery: "Flags",
    tab_quiz: "Quiz",
    // The gallery
    gallery_blurb: "Every flag in the package. Search by name in English or Japanese, or by code; narrow it to a country's regions or a continent; and see the frames the package draws without stretching a flag.",
    search: "Find",
    search_hint: "Tokyo, 東京, Ontario, JP-13 …",
    set: "Which flags",
    set_all: "All",
    set_country: "Countries",
    set_jp: "Japan",
    set_ca: "Canada",
    set_us: "United States",
    set_au: "Australia",
    set_gb: "United Kingdom",
    set_de: "Germany",
    set_fr: "France",
    set_ch: "Switzerland",
    set_at: "Austria",
    set_br: "Brazil",
    region: "Continent",
    region_all: "Every continent",
    shape: "Shape",
    shape_flag: "Own",
    shape_43: "4:3",
    shape_11: "1:1",
    shape_round: "Round",
    count: "{shown} of {total} flags",
    download_list: "List (TXT)",
    download_manifest: "Manifest (JSON)",
    empty: "No flag matches. Try a code, or another spelling.",
    left_out_title: "Places with no flag here ({n})",
    left_out_blurb: "Every country and region Kuni knows has a flag here or is listed with the reason (in English, as the package gives it).",
    // The detail panel
    close: "Close",
    frames_title: "Framed without misrepresenting it, by flag(code, { shape })",
    frame_43: "4:3",
    frame_11: "Square",
    frame_round: "Round",
    method_own: "its own shape",
    method_adapted: "drawn for the shape by flag-icons",
    method_cover: "cropped, keeping every colour",
    method_hoist: "cropped from the fly",
    method_contain: "whole: a crop would lose a colour",
    embed_title: "Embed this flag",
    embed_blurb: "Choose how it looks, and copy the code for your page: a <hata-flag> element, an <img>, an iframe, or for React, Vue, Svelte or Angular.",
    fact_code: "Code",
    fact_ratio: "Proportions",
    fact_size: "Size",
    fact_size_value: "{bytes} of SVG, {gzip} gzipped",
    fact_source: "Drawing from",
    fact_why: "Why this drawing",
    fact_file: "File",
    fact_author: "Author",
    fact_licence: "Licence",
    fact_reference: "Compared with",
    fact_restrictions: "Restrictions",
    fact_dates: "Dates",
    fact_dates_value: "uploaded {uploaded}, fetched {fetched}",
    fact_dates_set: "{source} {version}, read {fetched}",
    fact_shared: "Shares its picture with",
    fact_notes: "Note",
    none: "none",
    source_commons: "Wikimedia Commons",
    source_set: "{source}, an MIT flag set",
    copy_title: "Use it",
    copy_import: "Import the module",
    copy_load: "Load it by code",
    copy_img: "An <img> from the CDN",
    copy_svg: "The SVG itself",
    copy: "Copy",
    copied: "Copied to the clipboard.",
    copy_failed: "This browser would not copy; the text is selected, so copy it by hand.",
    download_title: "Download",
    download_svg: "SVG",
    png_size: "PNG width",
    download_png: "PNG",
    download_json: "Record (JSON)",
    tile: "{name}, {code}",
    // The quiz
    quiz_blurb: "Ten flags, four names each. The same seed always asks the same flags in the same order, so a link to your game gives a friend the very same ten.",
    mode: "Ask about",
    mode_country: "Countries",
    mode_jp: "Prefectures",
    mode_ca: "Provinces",
    mode_us: "States",
    mode_au: "Australia's states and territories",
    mode_br: "Brazil's states",
    mode_de: "Germany's states",
    mode_ch: "Swiss cantons",
    mode_europe: "Europe's regions",
    seed: "Seed",
    new_game: "New game",
    daily: "Today's",
    share: "Share link",
    score: "right",
    streak: "in a row",
    best: "best run",
    choices: "Which place is this?",
    progress: "Flag {n} of {total}",
    question: "Whose flag is this?",
    right: "Right: {name}.",
    wrong: "Not quite: that is {name}.",
    next: "Next flag",
    finish: "See the score",
    again: "Play again",
    done: "You named {score} of {total}. Play the same ten again, start a new game, or share the link.",
    shared: "Link copied: {url}",
    share_failed: "The link to share: {url}",
  },
  ja: {
    pageApi: "API（英語）",
    pitch: "世界の国々と、日本・カナダ・アメリカ・オーストラリア・イギリス・ドイツ・フランス・スイス・オーストリア・ブラジルの地域の旗を、本来の縦横比の SVG で収録し、ISO 3166 のコードで引けるようにしたパッケージです。旗をタップすると、出典、ライセンス、埋め込み用のコード、ダウンロードが表示されます。クイズもあります。",
    name: "Hata は、国や地域のしるしとして掲げる「旗（はた）」のことです。",
    nameLink: "名前について（英語）",
    foot: "旗はすべて、パッケージ自身のファイルを使って、お使いのブラウザ上で表示しています。このページの外にデータが送られることはありません。",
    moreTitle: "使い方",
    moreText: "旗は一つずつ別のモジュールなので、ページには読み込んだ旗だけが含まれます。ISO コードで旗を引く関数は、必要になったときにその旗だけを読み込みます。下の各行がそのまま使えるコードです。",
    tab_gallery: "旗の一覧",
    tab_quiz: "クイズ",
    gallery_blurb: "パッケージに含まれるすべての旗です。英語名・日本語名・コードで検索し、国ごとの地域や大陸で絞り込めます。旗を引き伸ばさずに枠に収める表示も試せます。",
    search: "検索",
    search_hint: "東京、Tokyo、オンタリオ、JP-13 …",
    set: "表示する旗",
    set_all: "すべて",
    set_country: "国",
    set_jp: "日本",
    set_ca: "カナダ",
    set_us: "アメリカ",
    set_au: "オーストラリア",
    set_gb: "イギリス",
    set_de: "ドイツ",
    set_fr: "フランス",
    set_ch: "スイス",
    set_at: "オーストリア",
    set_br: "ブラジル",
    region: "大陸",
    region_all: "すべての大陸",
    shape: "形",
    shape_flag: "旗のまま",
    shape_43: "4:3",
    shape_11: "1:1",
    shape_round: "円形",
    count: "{total} 件中 {shown} 件",
    download_list: "一覧（TXT）",
    download_manifest: "マニフェスト（JSON）",
    empty: "該当する旗がありません。コードや別の表記もお試しください。",
    left_out_title: "旗を収録していない地域（{n}）",
    left_out_blurb: "Kuni に含まれる国と地域は、すべて旗を収録しているか、ここに理由とともに載っています（理由は英語で、パッケージの記載のままです）。",
    close: "閉じる",
    frames_title: "flag(code, { shape }) で、旗の姿を損なわずに枠に収めた形",
    frame_43: "4:3",
    frame_11: "正方形",
    frame_round: "円形",
    method_own: "本来の形",
    method_adapted: "flag-icons がこの形用に描いた図",
    method_cover: "切り抜き（どの色も残る）",
    method_hoist: "旗竿側を残して切り抜き",
    method_contain: "全体を表示（切り抜くと色が欠けるため）",
    embed_title: "この旗を埋め込む",
    embed_blurb: "見た目を選ぶと、ページに貼るコードをコピーできます。<hata-flag> 要素、<img>、iframe のほか、React・Vue・Svelte・Angular 用のコードもあります。",
    fact_code: "コード",
    fact_ratio: "縦横比",
    fact_size: "サイズ",
    fact_size_value: "SVG {bytes}、gzip 圧縮で {gzip}",
    fact_source: "図版の出典",
    fact_why: "この図版を選んだ理由",
    fact_file: "ファイル",
    fact_author: "作者",
    fact_licence: "ライセンス",
    fact_reference: "比較した図版",
    fact_restrictions: "制限",
    fact_dates: "日付",
    fact_dates_value: "アップロード {uploaded}、取得 {fetched}",
    fact_dates_set: "{source} {version}、{fetched} に取得",
    fact_shared: "同じ図版を使う地域",
    fact_notes: "備考",
    none: "なし",
    source_commons: "ウィキメディア・コモンズ",
    source_set: "{source}（MIT ライセンスの旗のセット）",
    copy_title: "使い方",
    copy_import: "モジュールを読み込む",
    copy_load: "ISO コードで読み込む",
    copy_img: "CDN の画像を <img> で使う",
    copy_svg: "SVG そのもの",
    copy: "コピー",
    copied: "クリップボードにコピーしました。",
    copy_failed: "このブラウザではコピーできませんでした。テキストを選択してあるので、手動でコピーしてください。",
    download_title: "ダウンロード",
    download_svg: "SVG",
    png_size: "PNG の幅",
    download_png: "PNG",
    download_json: "レコード（JSON）",
    tile: "{name}（{code}）",
    quiz_blurb: "旗を見て、4つの選択肢から名前を選ぶ10問のクイズです。同じシードからは、いつも同じ旗が同じ順で出題されます。ゲームのリンクを送れば、友だちもまったく同じ10問に挑戦できます。",
    mode: "出題範囲",
    mode_country: "国",
    mode_jp: "都道府県",
    mode_ca: "カナダの州・準州",
    mode_us: "アメリカの州",
    mode_au: "オーストラリアの州・準州",
    mode_br: "ブラジルの州",
    mode_de: "ドイツの州",
    mode_ch: "スイスの州",
    mode_europe: "ヨーロッパの地域",
    seed: "シード",
    new_game: "新しいゲーム",
    daily: "今日の問題",
    share: "リンクを共有",
    score: "正解",
    streak: "連続正解",
    best: "最高連続正解",
    choices: "名前の選択肢",
    progress: "{total} 問中 {n} 問目",
    question: "これはどこの旗？",
    right: "正解！{name}です。",
    wrong: "残念！これは{name}の旗です。",
    next: "次の旗",
    finish: "結果を見る",
    again: "もう一度",
    done: "{total} 問中 {score} 問正解でした。同じ10問にもう一度挑戦したり、新しいゲームを始めたり、リンクを共有したりできます。",
    shared: "リンクをコピーしました：{url}",
    share_failed: "共有用のリンク：{url}",
  },
};
