// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Arab_Emirates.svg

/**
 * The flag of United Arab Emirates (アラブ首長国連邦), AE, as an SVG string: viewBox 12 by 6 (2:1), 202 B.
 * From Wikimedia Commons, "Flag of the United Arab Emirates.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ae";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 12 6\"><path fill=\"#00843d\" d=\"M0 0h12v6H0z\"/><path fill=\"#fff\" d=\"M0 2h12v4H0z\"/><path d=\"M0 4h12v2H0z\"/><path fill=\"#c8102e\" d=\"M0 0h3v6H0z\"/></svg>";

export { svg };
export default svg;
