// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/am.svg

/**
 * The flag of Armenia (アルメニア), AM, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 198 B.
 * The drawing `flag("AM", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/am.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#d90012\" d=\"M0 0h640v160H0z\"/><path fill=\"#0033a0\" d=\"M0 160h640v160H0z\"/><path fill=\"#f2a800\" d=\"M0 320h640v160H0z\"/></svg>";

export { svg };
export default svg;
