// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Angola.svg

/**
 * The flag of Angola (アンゴラ), AO, as an SVG string: viewBox 900 by 600 (3:2), 1.5 KB.
 * From Wikimedia Commons, "Flag of Angola.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ao";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path d=\"M0 0h900v600H0z\"/><path fill=\"#cc092f\" d=\"M0 0h900v300H0z\"/><path fill=\"#ffcb00\" fill-rule=\"evenodd\" d=\"M390.9 205.8h36.6l11.1-34.5 11.4 34.5h36.7l-29.5 22 11.4 35-30-21.3L409 263l11.4-35.2z\"/><path fill=\"#ffcb00\" fill-rule=\"evenodd\" d=\"M524.8 394.7 496 372.2c29.1-23.7 48-60 48-100.6 0-61.9-44.1-113.9-102.4-126.2l4.5-21c8.1 1.8 17.6 5.2 25.5 8l7.5-12.7c8 4 17 7.8 24.6 12.6l-5.7 13.5c7.5 4.9 16.6 12.3 21.6 18.2l11.3-8.9c6 6.7 13.2 13.6 18.3 20.8L539 186.4c6.6 9.7 9.1 14.1 14 25.3l14.3-3.4c2.7 8.4 6.8 18.7 8.3 27.4l-13.5 5.3c1.6 6.8 3.7 18.6 3.6 28.6l-.1 1.8 14.2 2c-.6 8.8-1 18.7-2.7 27.4h-14.8c-2 9-4.8 20-8 28.4l12.2 7.2c-3.9 7.8-7.8 17.2-12.9 24.7l-13.5-5.7a167 167 0 0 1-17.1 21.3l8.7 11.4q-3.5 3-6.9 6.6m-63.4-2.7 21.8 13.1c-2 1.9-8.1 5-9.7 5.7l3.5 13.6c-8.4 2.7-17.4 6.6-26.7 8.4l-5.4-13.5q-13 2.8-26.4 3l-1.8 14.1c-8.4-.6-18.6 0-28-2v-14.2q-12.6-2.2-24.3-6.3l-6.9 12.3c-7.2-3-16.8-6.6-24.6-11.4l5.1-13.5c-6.3-3.3-12-7.5-17.4-11.7l13.5-17.1a129 129 0 0 0 80.8 28.2 121 121 0 0 0 46.5-8.7\"/><path fill=\"#ffcb00\" fill-rule=\"evenodd\" d=\"M552.2 426.8 408.5 317.4l-1.3 1.9 143.3 109.6-8.5 10.6L402.2 350c-37.8-23.7-36.3-42.4-28.5-62.5l6.6-16.2c3.6 21 25.3 37 47.8 54.7L555 423.3zm36 32.6a2 2 0 0 1-2.2-2.2 2.2 2.2 0 0 1 2.3-2.3q2 .2 2.2 2.3a2 2 0 0 1-2.2 2.2m-8.6-6.3a2.2 2.2 0 0 1-2.3-2.2 2.2 2.2 0 1 1 2.3 2.2m-8.8-7q-2-.2-2.2-2.2a2.2 2.2 0 0 1 4.4 0q-.2 2-2.2 2.2m29.6 12.4-43.1-33.4-12.5 16.2 37.4 26.2c3 2 3.3 11.7 14.4 13.2 4.5.6 7.5-2.7 7.5-2.7 4.8-5.9 3.5-14-3.8-19.5\"/></svg>";

export { svg };
export default svg;
