// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Tirol_and_Upper_Austria.svg, the same drawing as AT-4's flag.

import { svg as shared } from "./at-4";

/**
 * The flag of Tyrol (チロル州), AT-7, as an SVG string: viewBox 600 by 400 (3:2), 168 B. The same picture as AT-4's.
 * From Wikimedia Commons, "Flag of Tirol and Upper Austria.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/at-7";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
