// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_Northern_Territory.svg

/**
 * The flag of Northern Territory (ノーザンテリトリー), AU-NT, as an SVG string: viewBox 1200 by 600 (2:1), 1.5 KB.
 * From Wikimedia Commons, "Flag of the Northern Territory.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/au-nt";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"au-nt\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 600\"><path fill=\"#c75b12\" d=\"M0 0h1200v600H0z\"/><path d=\"M0 0h400v600H0z\"/><g id=\"hata-au-nt-b\" transform=\"translate(200,450)\"><path id=\"hata-au-nt-a\" fill=\"#fff\" d=\"M0-45 18 0 0 45-18 0Z\"/><use href=\"#hata-au-nt-a\" transform=\"rotate(90)\"/></g><use href=\"#hata-au-nt-b\" transform=\"rotate(45,200,450)\"/><path id=\"hata-au-nt-c\" fill=\"#fff\" d=\"m0-40 10 18 22-3-9 20L39 9l-20 6-1 21L0 24l-18 12-1-21-20-6 16-14-9-20 22 3z\" transform=\"translate(81 276)\"/><use x=\"119\" y=\"-126\" href=\"#hata-au-nt-c\"/><path id=\"hata-au-nt-d\" fill=\"#fff\" d=\"m306 216 12 15v42l-12 15-12-15v-42z\"/><use href=\"#hata-au-nt-d\" transform=\"rotate(60,306,252)\"/><use href=\"#hata-au-nt-d\" transform=\"rotate(120,306,252)\"/><path fill=\"#fff\" d=\"m246 288 8 13 15 4-10 11 1 15-14-5-14 5 1-15-10-11 15-4z\"/><g transform=\"translate(800 300) scale(0.04)\"><g id=\"hata-au-nt-e\"><path d=\"M-802-1666A975 975 0 0 0 0-1200a975 975 0 0 0 802-466L0 300z\"/><path fill=\"#fff\" d=\"M0-3750a1860 1860 0 0 1 638 150 720 720 0 0 1 412 650 2175 2175 0 0 1-150 800 1260 1260 0 0 1-675 743 525 525 0 0 1-225 57 525 525 0 0 1-225-57 1260 1260 0 0 1-675-743 2175 2175 0 0 1-150-800 720 720 0 0 1 413-650A1860 1860 0 0 1 0-3750\"/></g><g id=\"hata-au-nt-f\"><use href=\"#hata-au-nt-e\" transform=\"rotate(51.428571428571)\"/><use href=\"#hata-au-nt-e\" transform=\"rotate(102.857142857143)\"/><use href=\"#hata-au-nt-e\" transform=\"rotate(154.285714285714)\"/></g><use href=\"#hata-au-nt-f\" transform=\"rotate(154.285714285714)\"/></g></svg>";

export { svg };
export default svg;
