// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/ax.svg

/**
 * The flag of Åland Islands (オーランド諸島), AX, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 440 B.
 * The drawing `flag("AX", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/ax.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-ax-1x1-a\"><path d=\"M166 0h850v850H166z\"/></clipPath></defs><g clip-path=\"url(#hata-ax-1x1-a)\" transform=\"translate(-100)scale(.6024)\"><path fill=\"#0053a5\" d=\"M0 0h1300v850H0z\"/><g fill=\"#ffce00\"><path d=\"M400 0h250v850H400z\"/><path d=\"M0 300h1300v250H0z\"/></g><g fill=\"#d21034\"><path d=\"M475 0h100v850H475z\"/><path d=\"M0 375h1300v100H0z\"/></g></g></svg>";

export { svg };
export default svg;
