// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/az.svg

/**
 * The flag of Azerbaijan (アゼルバイジャン), AZ, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 449 B.
 * The drawing `flag("AZ", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/az.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#3f9c35\" d=\"M0 0h512v512H0z\"/><path fill=\"#ed2939\" d=\"M0 0h512v341.3H0z\"/><path fill=\"#00b9e4\" d=\"M0 0h512v170.7H0z\"/><circle cx=\"238.8\" cy=\"256\" r=\"76.8\" fill=\"#fff\"/><circle cx=\"255.9\" cy=\"256\" r=\"64\" fill=\"#ed2939\"/><path fill=\"#fff\" d=\"m324.2 213.3 8.1 23 22-10.5-10.4 22 23 8.2-23 8.2 10.4 22-22-10.5-8.1 23-8.2-23-22 10.5 10.5-22-23-8.2 23-8.2-10.5-22 22 10.5z\"/></svg>";

export { svg };
export default svg;
