// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Azerbaijan.svg

/**
 * The flag of Azerbaijan (アゼルバイジャン), AZ, as an SVG string: viewBox 1200 by 600 (2:1), 416 B.
 * From Wikimedia Commons, "Flag of Azerbaijan.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/az";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 600\"><path fill=\"#509e2f\" d=\"M0 0h1200v600H0z\"/><path fill=\"#ef3340\" d=\"M0 0h1200v400H0z\"/><path fill=\"#00b5e2\" d=\"M0 0h1200v200H0z\"/><circle cx=\"570\" cy=\"300\" r=\"90\" fill=\"#fff\"/><circle cx=\"590\" cy=\"300\" r=\"75\" fill=\"#ef3340\"/><path fill=\"#fff\" d=\"m670 250 10 27 25-12-12 25 27 10-27 10 12 25-25-12-10 27-10-27-25 12 12-25-27-10 27-10-12-25 25 12z\"/></svg>";

export { svg };
export default svg;
