// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/bd.svg

/**
 * The flag of Bangladesh (バングラデシュ), BD, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 160 B.
 * The drawing `flag("BD", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/bd.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#006a4e\" d=\"M0 0h640v480H0z\"/><circle cx=\"280\" cy=\"240\" r=\"160\" fill=\"#f42a41\"/></svg>";

export { svg };
export default svg;
