// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Bangladesh.svg

/**
 * The flag of Bangladesh (バングラデシュ), BD, as an SVG string: viewBox 10 by 6 (5:3), 150 B.
 * From Wikimedia Commons, "Flag of Bangladesh.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/bd";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 6\"><path fill=\"#006747\" d=\"M0 0h10v6H0z\"/><circle cx=\"4.5\" cy=\"3\" r=\"2\" fill=\"#da291c\"/></svg>";

export { svg };
export default svg;
