// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Burkina_Faso.svg

/**
 * The flag of Burkina Faso (ブルキナファソ), BF, as an SVG string: viewBox 900 by 600 (3:2), 534 B.
 * From Wikimedia Commons, "Flag of Burkina Faso.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/bf";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#009e49\" d=\"M0 0h900v600H0z\"/><path fill=\"#ef2b2d\" d=\"M0 0h900v300H0z\"/><g fill=\"#fcd116\" transform=\"translate(450,300)\"><g id=\"hata-bf-b\"><path id=\"hata-bf-a\" d=\"M0-100V0h50\" transform=\"rotate(18 0,-100)\"/><use href=\"#hata-bf-a\" transform=\"scale(-1,1)\"/></g><use href=\"#hata-bf-b\" transform=\"rotate(72)\"/><use href=\"#hata-bf-b\" transform=\"rotate(144)\"/><use href=\"#hata-bf-b\" transform=\"rotate(216)\"/><use href=\"#hata-bf-b\" transform=\"rotate(288)\"/></g></svg>";

export { svg };
export default svg;
