// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Burundi.svg

/**
 * The flag of Burundi (ブルンジ), BI, as an SVG string: viewBox 100 by 60 (5:3), 626 B.
 * From Wikimedia Commons, "Flag of Burundi.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/bi";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"bi\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#c8102e\" viewBox=\"-50 -30 100 60\"><title>Flag of Burundi</title><defs><clipPath id=\"hata-bi-a\"><path d=\"M-50-30H50v60H-50z\"/></clipPath></defs><path d=\"M-50-30H50v60H-50z\"/><path fill=\"#43b02a\" stroke=\"#fff\" stroke-width=\"8\" d=\"M-55-33v66L55-33v66z\" clip-path=\"url(#hata-bi-a)\"/><circle r=\"17\" fill=\"#fff\"/><path id=\"hata-bi-b\" stroke=\"#43b02a\" stroke-width=\".36\" d=\"m0-12.44 1.05 1.82h2.1L2.1-8.8l1.05 1.82h-2.1L0-5.16l-1.05-1.82h-2.1L-2.1-8.8l-1.05-1.82h2.1z\"/><use href=\"#hata-bi-b\" transform=\"rotate(120)\"/><use href=\"#hata-bi-b\" transform=\"rotate(240)\"/></svg>";

export { svg };
export default svg;
