// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Goi%C3%A1s.svg

/**
 * The flag of Goiás (ゴイアス州), BR-GO, as an SVG string: viewBox 560 by 392 (10:7), 738 B.
 * From Wikimedia Commons, "Flag of Goiás.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/br-go";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 560 392\"><path fill=\"#1fa22e\" fill-rule=\"evenodd\" d=\"M0 0h560v392H0z\"/><path fill=\"#fd0\" fill-rule=\"evenodd\" d=\"M0 49h560v49H0z\"/><path fill=\"#00519e\" d=\"M0 0h196v147H0z\"/><path fill=\"#fff\" d=\"M111.8 94.8 98 84.8l-13.8 10 5.3-16.3-13.8-10h17L98 52.2l5.3 16.3h17l-13.8 10zm-54 41.4-18.3-13.4L21 136.2l7-21.7-18.3-13.4h22.6l7-21.7 7 21.7h22.8l-18.4 13.4zm0-68.6L39.5 54.2 21 67.6l7-21.7L9.8 32.5h22.6l7-21.7 7 21.7h22.8L50.8 45.9zm117.1 0-18.4-13.4-18.3 13.4 7-21.7-18.4-13.4h22.7l7-21.7 7 21.7h22.7L168 45.9zm0 68.6-18.4-13.4-18.3 13.4 7-21.7-18.4-13.4h22.7l7-21.7 7 21.7h22.7L168 114.5z\"/><path fill=\"#fd0\" fill-rule=\"evenodd\" d=\"M0 147h560v49H0zm0 98h560v49H0zm0 98h560v49H0z\"/></svg>";

export { svg };
export default svg;
