// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Bandeira_do_Maranh%C3%A3o.svg

/**
 * The flag of Maranhão (マラニョン州), BR-MA, as an SVG string: viewBox 1350 by 900 (3:2), 882 B.
 * From Wikimedia Commons, "Bandeira do Maranhão.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/br-ma";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1350 900\"><defs><g id=\"hata-br-ma-c\" transform=\"scale(168.75)\"><g id=\"hata-br-ma-b\"><path id=\"hata-br-ma-a\" fill=\"#fff\" d=\"M0 0v1h.5z\" transform=\"translate(0,-1) rotate(18)\"/><use href=\"#hata-br-ma-a\" transform=\"scale(-1,1)\"/></g><use href=\"#hata-br-ma-b\" transform=\"rotate(72)\"/><use href=\"#hata-br-ma-b\" transform=\"rotate(-72)\"/><use href=\"#hata-br-ma-b\" transform=\"rotate(144)\"/><use href=\"#hata-br-ma-b\" transform=\"rotate(-144)\"/></g></defs><rect width=\"100%\" height=\"100%\" fill=\"#fff\"/><rect width=\"100%\" height=\"100\" fill=\"#c53425\"/><rect width=\"100%\" height=\"100\" y=\"400\" fill=\"#c53425\"/><rect width=\"100%\" height=\"100\" y=\"800\" fill=\"#c53425\"/><rect width=\"100%\" height=\"100\" y=\"200\"/><rect width=\"100%\" height=\"100\" y=\"600\"/><rect width=\"450\" height=\"50%\" fill=\"#25247b\"/><use x=\"225\" y=\"225\" href=\"#hata-br-ma-c\"/></svg>";

export { svg };
export default svg;
