// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Bandeira_do_Par%C3%A1.svg

/**
 * The flag of Pará (パラー州), BR-PA, as an SVG string: viewBox 900 by 600 (3:2), 655 B.
 * From Wikimedia Commons, "Bandeira do Pará.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/br-pa";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"br-pa\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path d=\"M0 0h900v600H0z\" style=\"fill:#fff;fill-opacity:1;stroke:none;stroke-width:5;stroke-miterlimit:4;stroke-dashoffset:0;stroke-opacity:1\"/><path d=\"M0 0h900v600H0z\" style=\"fill:#eb2939;fill-opacity:1;stroke:none;stroke-opacity:1\"/><path d=\"M0 0h180l720 507v93H720L0 92.6z\" style=\"fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"/><path d=\"m497 364.7-47-34.1-47 34.1 18-55.3-47-34.1h58l18-55.3 18 55.3h58l-47 34.1z\" style=\"fill:#0071ce;fill-opacity:1;stroke:none;stroke-opacity:1\"/></svg>";

export { svg };
export default svg;
