// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Bandeira_do_Tocantins.svg

/**
 * The flag of Tocantins (トカンティンス州), BR-TO, as an SVG string: viewBox 20 by 14 (10:7), 495 B.
 * From Wikimedia Commons, "Bandeira do Tocantins.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/br-to";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"br-to\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"gold\" viewBox=\"0 0 20 14\"><path fill=\"#fff\" d=\"M0 0h20v14H0\"/><path fill=\"#1946b4\" d=\"M13 0H0v9\"/><path d=\"M7 14h13V5\"/><g id=\"hata-br-to-c\"><g id=\"hata-br-to-b\"><path id=\"hata-br-to-a\" d=\"m9.08 5.69-.19-.71.5.54-.03-.73.36.63L10 3l.28 2.42L10 7.04\"/><use href=\"#hata-br-to-a\" transform=\"rotate(45 10 7)\"/></g><use href=\"#hata-br-to-b\" transform=\"rotate(90 10 7)\"/></g><use href=\"#hata-br-to-c\" transform=\"rotate(180 10 7)\"/></svg>";

export { svg };
export default svg;
