// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/bw.svg

/**
 * The flag of Botswana (ボツワナ), BW, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 222 B.
 * The drawing `flag("BW", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/bw.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><g fill-rule=\"evenodd\"><path fill=\"#00cbff\" d=\"M0 0h640v480H0z\"/><path fill=\"#fff\" d=\"M0 160h640v160H0z\"/><path fill=\"#000001\" d=\"M0 186h640v108H0z\"/></g></svg>";

export { svg };
export default svg;
