// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/cd.svg

/**
 * The flag of Congo - Kinshasa (コンゴ民主共和国(キンシャサ)), CD, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 451 B.
 * The drawing `flag("CD", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/cd.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-cd-1x1-a\"><path fill=\"#fff\" d=\"M0-88h600v600H0z\"/></clipPath></defs><g clip-path=\"url(#hata-cd-1x1-a)\" transform=\"translate(0 75.1)scale(.853)\"><path fill=\"#007fff\" d=\"M0-88h800v600H0z\"/><path fill=\"#f7d618\" d=\"M36 32h84l26-84 26 84h84l-68 52 26 84-68-52-68 52 26-84zM750-88 0 362v150h50L800 62V-88z\"/><path fill=\"#ce1021\" d=\"M800-88 0 392v120L800 32z\"/></g></svg>";

export { svg };
export default svg;
