// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_Democratic_Republic_of_the_Congo.svg

/**
 * The flag of Congo - Kinshasa (コンゴ民主共和国(キンシャサ)), CD, as an SVG string: viewBox 800 by 600 (4:3), 294 B.
 * From Wikimedia Commons, "Flag of the Democratic Republic of the Congo.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/cd";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 800 600\"><path d=\"M0 0h800v600H0z\" style=\"fill:#007fff\"/><path d=\"M36 120h84l26-84 26 84h84l-68 52 26 84-68-52-68 52 26-84zM750 0 0 450v150h50l750-450V0z\" style=\"fill:#f7d618\"/><path d=\"M800 0 0 480v120l800-480z\" style=\"fill:#ce1021\"/></svg>";

export { svg };
export default svg;
