// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/cf.svg

/**
 * The flag of Central African Republic (中央アフリカ共和国), CF, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 573 B.
 * The drawing `flag("CF", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/cf.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-cf-1x1-a\"><path fill-opacity=\".7\" d=\"M0 0h512v512H0z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-cf-1x1-a)\"><path fill=\"#00f\" d=\"M-52-.5h768v127H-52z\"/><path fill=\"#ff0\" d=\"M-52 383.5h768V512H-52z\"/><path fill=\"#009a00\" d=\"M-52 255h768v128.5H-52z\"/><path fill=\"#fff\" d=\"M-52 126.5h768V255H-52z\"/><path fill=\"red\" d=\"M268 0h128v512H268z\"/><path fill=\"#ff0\" d=\"M109.5 112.3 75.9 89.1l-33.4 23.4 11.6-39.2-32.5-24.6 40.7-1L75.7 8.8l13.5 38.6 40.8.8L97.6 73\"/></g></svg>";

export { svg };
export default svg;
