// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/cf.svg

/**
 * The flag of Central African Republic (中央アフリカ共和国), CF, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 625 B.
 * The drawing `flag("CF", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/cf.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-cf-4x3-a\"><path fill-opacity=\".7\" d=\"M-12.4 32h640v480h-640z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-cf-4x3-a)\" transform=\"translate(12.4 -32)\"><path fill=\"#00f\" d=\"M-52 32h719.3v119H-52z\"/><path fill=\"#ff0\" d=\"M-52 391.6h719.3V512H-52z\"/><path fill=\"#009a00\" d=\"M-52 271.3h719.3v120.3H-52z\"/><path fill=\"#fff\" d=\"M-52 151h719.3v120.3H-52z\"/><path fill=\"red\" d=\"M247.7 32.5h119.9V512H247.7z\"/><path fill=\"#ff0\" d=\"m99.3 137.7-31.5-21.8-31.3 22L47.4 101 16.9 78l38.2-1 12.5-36.3L80.3 77l38.1.7L88.2 101\"/></g></svg>";

export { svg };
export default svg;
