// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:CHE_Aargau_Flag.svg

/**
 * The flag of Aargau (アールガウ州), CH-AG, as an SVG string: viewBox 500 by 500 (1:1), 1.7 KB.
 * From Wikimedia Commons, "CHE Aargau Flag.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ch-ag";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" xml:space=\"preserve\" viewBox=\"0 0 500 500\"><path d=\"M0 0h500v500H0z\"/><path fill=\"#268bcc\" d=\"M252.15 0H500v500H252.15z\" style=\"fill:#0093dd;fill-opacity:1\"/><path d=\"M239.29-16.16h36.93l-29.18 20 11.12 35.82-32.77-21.1-32.79 21.1 11.38-36.11-29.44-19.71h36.95l13.9-37.77zm-77.4 0-29.16 20 11.1 35.82-32.78-21.1-32.51 21.1 11.1-36.11-29.43-19.71h36.95l13.89-37.77 13.9 37.77zm20.14 99.98h36.95l-29.43 19.74 11.39 36.1-32.8-21.1-32.79 20.81 11.1-35.81-29.16-20h36.95l13.9-37.5z\" style=\"fill:#fff;stroke-width:3.452;stroke:#000;stroke-dasharray:none\" transform=\"translate(206.827 207.477)\"/><path d=\"M250 223.5c-12.32-2.35-14.33-10.85-33.2-10.85-21.93 0-18.6 11.81-44.8 11.81s-23.5-11.81-45.44-11.81-20.3 11.81-45.53 11.81-22.77-11.81-44.7-11.81c-20.4 0-21.1 9.9-36.33 11.3V186.3c15.22-1.4 15.93-11.3 36.33-11.3 21.93 0 19.47 11.81 44.7 11.81 25.22 0 23.6-11.81 45.53-11.81s19.24 11.81 45.44 11.81S194.87 175 216.8 175c18.87 0 20.9 8.5 33.2 10.88zm0 50.28c-12.32-2.34-14.33-10.86-33.2-10.86-21.93 0-18.6 11.82-44.8 11.82s-23.5-11.82-45.44-11.82-20.3 11.82-45.53 11.82-22.77-11.82-44.7-11.82c-20.4 0-21.1 9.9-36.33 11.3v-37.64c15.22-1.4 15.93-11.3 36.33-11.3 21.93 0 19.47 11.82 44.7 11.82 25.22 0 23.6-11.82 45.53-11.82S145.8 237.1 172 237.1s22.87-11.82 44.8-11.82c18.87 0 20.9 8.5 33.2 10.86zm0 50.28c-12.32-2.37-14.33-10.86-33.2-10.86-21.93 0-18.6 11.8-44.8 11.8s-23.5-11.8-45.44-11.8-20.3 11.8-45.53 11.8-22.77-11.8-44.7-11.8c-20.4 0-21.1 9.9-36.33 11.29v-37.64c15.22-1.39 15.93-11.3 36.33-11.3 21.93 0 19.47 11.8 44.7 11.8 25.22 0 23.6-11.8 45.53-11.8s19.24 11.8 45.44 11.8 22.87-11.8 44.8-11.8c18.87 0 20.9 8.5 33.2 10.87z\" style=\"fill:#fff;stroke-width:1.08469\" transform=\"scale(0.99079755,1)\"/></svg>";

export { svg };
export default svg;
