// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Canton_of_Fribourg.svg

/**
 * The flag of Fribourg (フリブール州), CH-FR, as an SVG string: viewBox 600 by 600 (1:1), 134 B.
 * From Wikimedia Commons, "Flag of Canton of Fribourg.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ch-fr";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 600 600\"><path fill=\"#fff\" d=\"M0 0h600v600H0z\"/><path d=\"M0 0h600v300H0z\"/></svg>";

export { svg };
export default svg;
