// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:CHE_Jura_Flag.svg

/**
 * The flag of Jura (ジュラ州), CH-JU, as an SVG string: viewBox 350 by 350 (1:1), 1.6 KB.
 * From Wikimedia Commons, "CHE Jura Flag.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ch-ju";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" xml:space=\"preserve\" viewBox=\"-204.866 -205.348 350 350\"><g style=\"overflow:visible\"><path fill=\"#fff\" d=\"m145.116 144.492-349.982.16v-349.858l350-.142z\"/><path fill=\"#e53328\" d=\"M105.4 30.606h10.173v2.898H105.4zm0 5.792h10.173v2.903H105.4zm0 5.801h10.173v2.897H105.4zm0-17.407h10.173v2.894H105.4z\" style=\"stroke-width:1.04044978;stroke:none;stroke-dasharray:none;fill:#f00000;fill-opacity:1\" transform=\"matrix(17.249027,0,0,17.237983,-1848.3878,-632.71207)\"/><path stroke-width=\"3.516\" d=\"M29.12-205.376v469.59\" style=\"overflow:visible;stroke:#000;stroke-opacity:1\" transform=\"matrix(17.249027,0,0,17.237983,-1848.3878,-632.71207) matrix(0.0431538,0,0,0.04323775,104.21893,33.671983)\"/><path fill=\"#e53328\" d=\"M-28.59-119.793c-4.99-47.03-28.226-66.277-65.436-66.277-37.327.044-56.408 26.053-56.408 51.523 0 15.813 9.285 38 33.264 38 23.98-.022 32.22-14.67 32.22-26.335 0-11.493-11.073-20.22-20.985-20.22-9.888 0-16.365 4.126-16.365 4.126 2.484-16.267 15.831-19.313 24.118-19.313 12.327 0 28.83 7.669 28.83 37.006 0 9.181-4.317 44.07-10.747 87.664h62.675c-5.385-39.425-9.75-72.326-11.165-86.174zm-86.746 319.399L-73.9 123.65l25.279 72.305 23.91-72.78 42.595 76.604S2.307 107.081-9.276 23.305l-78.9.021c-12.675 85.396-27.16 176.28-27.16 176.28zM11.453-9.812V.88h-120.01l-.023-10.585zM-1.29 6.973v10.478l-94.802.044V6.93Zm0-34.046v10.456l-94.802.044v-10.52h94.801z\" style=\"overflow:visible;fill:#f00000;fill-opacity:1;stroke:#000;stroke-width:2.23044;stroke-dasharray:none;stroke-opacity:1\" transform=\"matrix(17.249027,0,0,17.237983,-1848.3878,-632.71207) matrix(0.04438986,0,0,0.04767263,103.26369,34.696081)\"/></g></svg>";

export { svg };
export default svg;
