// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Switzerland.svg

/**
 * The flag of Switzerland (スイス), CH, as an SVG string: viewBox 32 by 32 (1:1), 173 B.
 * From Wikimedia Commons, "Flag of Switzerland.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ch";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"ch\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><path fill=\"red\" d=\"M0 0h32v32H0z\"/><path fill=\"#fff\" d=\"M13 6h6v7h7v6h-7v7h-6v-7H6v-6h7z\"/></svg>";

export { svg };
export default svg;
