// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/cn.svg

/**
 * The flag of China (中国), CN, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 744 B.
 * The drawing `flag("CN", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/cn.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><path id=\"hata-cn-4x3-a\" fill=\"#ff0\" d=\"M-.6.8 0-1 .6.8-1-.3h2z\"/></defs><path fill=\"#ee1c25\" d=\"M0 0h640v480H0z\"/><use width=\"30\" height=\"20\" href=\"#hata-cn-4x3-a\" transform=\"matrix(71.9991 0 0 72 120 120)\"/><use width=\"30\" height=\"20\" href=\"#hata-cn-4x3-a\" transform=\"matrix(-12.33562 -20.5871 20.58684 -12.33577 240.3 48)\"/><use width=\"30\" height=\"20\" href=\"#hata-cn-4x3-a\" transform=\"matrix(-3.38573 -23.75998 23.75968 -3.38578 288 95.8)\"/><use width=\"30\" height=\"20\" href=\"#hata-cn-4x3-a\" transform=\"matrix(6.5991 -23.0749 23.0746 6.59919 288 168)\"/><use width=\"30\" height=\"20\" href=\"#hata-cn-4x3-a\" transform=\"matrix(14.9991 -18.73557 18.73533 14.99929 240 216)\"/></svg>";

export { svg };
export default svg;
