// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/co.svg

/**
 * The flag of Colombia (コロンビア), CO, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 225 B.
 * The drawing `flag("CO", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/co.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><g fill-rule=\"evenodd\"><path fill=\"#ffe800\" d=\"M0 0h640v480H0z\"/><path fill=\"#00148e\" d=\"M0 240h640v240H0z\"/><path fill=\"#da0010\" d=\"M0 360h640v120H0z\"/></g></svg>";

export { svg };
export default svg;
