// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Costa_Rica.svg

/**
 * The flag of Costa Rica (コスタリカ), CR, as an SVG string: viewBox 10 by 6 (5:3), 179 B.
 * From Wikimedia Commons, "Flag of Costa Rica.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/cr";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 6\"><path fill=\"#001489\" d=\"M0 0h10v6H0z\"/><path fill=\"#fff\" d=\"M0 1h10v4H0z\"/><path fill=\"#da291c\" d=\"M0 2h10v2H0z\"/></svg>";

export { svg };
export default svg;
