// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/cu.svg

/**
 * The flag of Cuba (キューバ), CU, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 558 B.
 * The drawing `flag("CU", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/cu.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-cu-4x3-a\"><path fill-opacity=\".7\" d=\"M-32 0h682.7v512H-32z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-cu-4x3-a)\" transform=\"translate(30)scale(.94)\"><path fill=\"#002a8f\" d=\"M-32 0h768v512H-32z\"/><path fill=\"#fff\" d=\"M-32 102.4h768v102.4H-32zm0 204.8h768v102.4H-32z\"/><path fill=\"#cb1515\" d=\"m-32 0 440.7 255.7L-32 511z\"/><path fill=\"#fff\" d=\"M161.8 325.5 114.3 290l-47.2 35.8 17.6-58.1-47.2-36 58.3-.4 18.1-58 18.5 57.8 58.3.1-46.9 36.3z\"/></g></svg>";

export { svg };
export default svg;
