// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/cw.svg

/**
 * The flag of Curaçao (キュラソー), CW, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 609 B.
 * The drawing `flag("CW", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/cw.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-cw-1x1-a\"><path fill-opacity=\".7\" d=\"M0 0h9000v9000H0z\"/></clipPath><path id=\"hata-cw-1x1-b\" d=\"m0-1 .2.7H1L.3 0l.2.7L0 .4l-.6.4.2-.7-.5-.4h.7z\"/></defs><g clip-path=\"url(#hata-cw-1x1-a)\" transform=\"scale(.057)\"><path fill=\"#002b7f\" d=\"M0 0h13500v9000H0z\"/><path fill=\"#f9e814\" d=\"M0 5625h13500v1125H0z\"/><use width=\"13500\" height=\"9000\" x=\"2\" y=\"2\" fill=\"#fff\" href=\"#hata-cw-1x1-b\" transform=\"scale(750)\"/><use width=\"13500\" height=\"9000\" x=\"3\" y=\"3\" fill=\"#fff\" href=\"#hata-cw-1x1-b\" transform=\"scale(1000)\"/></g></svg>";

export { svg };
export default svg;
