// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_Czech_Republic.svg

/**
 * The flag of Czechia (チェコ), CZ, as an SVG string: viewBox 900 by 600 (3:2), 208 B.
 * From Wikimedia Commons, "Flag of the Czech Republic.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/cz";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"cz\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#d7141a\" d=\"M0 0h900v600H0z\"/><path fill=\"#fff\" d=\"M0 0h900v300H0z\"/><path fill=\"#11457e\" d=\"M450 300 0 0v600z\"/></svg>";

export { svg };
export default svg;
