// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Baden-W%C3%BCrttemberg.svg

/**
 * The flag of Baden-Württemberg (バーデン＝ヴュルテンベルク州), DE-BW, as an SVG string: viewBox 500 by 300 (5:3), 137 B.
 * From Wikimedia Commons, "Flag of Baden-Württemberg.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/de-bw";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 500 300\"><path fill=\"#f9c700\" d=\"M0 0h500v300H0z\"/><path d=\"M0 0h500v150H0z\"/></svg>";

export { svg };
export default svg;
