// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Bavaria_(striped).svg

/**
 * White and blue stripes: one of the flags of Bavaria (バイエルン自由州), DE-BY, in real use, as an SVG string: viewBox 10 by 6 (5:3), 167 B.
 * From Wikimedia Commons, "Flag of Bavaria (striped).svg" (public domain). `flag("DE-BY", { variant: "stripes" })` loads it, and `variantsOf("DE-BY")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/de-by--stripes";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = "<svg data-hata=\"de-by--stripes\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 6\"><path fill=\"#0098d4\" d=\"M0 0h10v6H0z\"/><path fill=\"#fff\" d=\"M0 0h10v3H0z\"/></svg>";

export { svg };
export default svg;
