// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Germany.svg

/**
 * The flag of Germany (ドイツ), DE, as an SVG string: viewBox 5 by 3 (5:3), 203 B.
 * From Wikimedia Commons, "Flag of Germany.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/de";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"de\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 5 3\"><desc>Flag of Germany</desc><path d=\"M0 0h5v3H0z\"/><path fill=\"#d00\" d=\"M0 1h5v2H0z\"/><path fill=\"#ffce00\" d=\"M0 2h5v1H0z\"/></svg>";

export { svg };
export default svg;
