// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Estonia.svg

/**
 * The flag of Estonia (エストニア), EE, as an SVG string: viewBox 990 by 630 (1.571:1), 180 B.
 * From Wikimedia Commons, "Flag of Estonia.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ee";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 990 630\"><path fill=\"#0072ce\" d=\"M0 0h990v315H0z\"/><path d=\"M0 210h990v315H0z\"/><path fill=\"#fff\" d=\"M0 420h990v210H0z\"/></svg>";

export { svg };
export default svg;
