// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/fm.svg

/**
 * The flag of Micronesia (ミクロネシア連邦), FM, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 554 B.
 * The drawing `flag("FM", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/fm.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-fm-4x3-a\"><path d=\"M-81 0h682v512H-81z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-fm-4x3-a)\" transform=\"translate(76.3)scale(.94)\"><path fill=\"#6797d6\" d=\"M-252 0H772v512H-252z\"/><path fill=\"#fff\" d=\"m260 123-33 22 13-36-33-22h40l13-36 12 36h40l-32 22 12 36m-32 245-33-22 13 36-33 22h40l13 36 12-36h40l-32-22 12-36m-188-93-25 31 2-38-38-12 39-11 1-38 22 30 39-11-25 30 22 31m275-12 24 31-1-38 37-12-38-11-1-38-23 30-38-11 25 30-23 31\"/></g></svg>";

export { svg };
export default svg;
