// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/fo.svg

/**
 * The flag of Faroe Islands (フェロー諸島), FO, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 508 B.
 * The drawing `flag("FO", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/fo.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-fo-4x3-a\"><path fill-opacity=\".7\" d=\"M-78 32h640v480H-78z\"/></clipPath></defs><g fill-rule=\"evenodd\" stroke-width=\"0\" clip-path=\"url(#hata-fo-4x3-a)\" transform=\"translate(78 -32)\"><path fill=\"#fff\" d=\"M-78 32h663.9v480H-78z\"/><path fill=\"#003897\" d=\"M-76 218.7h185.9V32H216v186.7h371.8v106.6H216V512H109.9V325.3h-186z\"/><path fill=\"#d72828\" d=\"M-76 245.3h212.4V32h53.1v213.3H588v53.4H189.5V512h-53V298.7H-76z\"/></g></svg>";

export { svg };
export default svg;
