// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Mayotte_(Local).svg, the same drawing as YT's flag.

import { svg as shared } from "./yt";

/**
 * The flag of Mayotte (マヨット), FR-976, as an SVG string: viewBox 750 by 500 (3:2), 52.5 KB. The same picture as YT's.
 * From Wikimedia Commons, "Flag of Mayotte (Local).svg" (CC0); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/fr-976";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
