// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Saint_Barth%C3%A9lemy_(local).svg, the same drawing as BL's flag.

import { svg as shared } from "./bl";

/**
 * The flag of St. Barthélemy (サン・バルテルミー), FR-BL, as an SVG string: viewBox 937.5 by 625 (3:2), 28.9 KB. The same picture as BL's.
 * From Wikimedia Commons, "Flag of Saint Barthélemy (local).svg" (CC BY 2.5); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/fr-bl";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
