// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_France.svg, the same drawing as FR's flag.

import { svg as shared } from "./fr";

/**
 * The flag of St. Martin (サン・マルタン), FR-MF, as an SVG string: viewBox 900 by 600 (3:2), 188 B. The same picture as FR's.
 * From Wikimedia Commons, "Flag of France.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/fr-mf";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
