// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_French_Polynesia.svg, the same drawing as PF's flag.

import { svg as shared } from "./pf";

/**
 * The flag of French Polynesia (仏領ポリネシア), FR-PF, as an SVG string: viewBox 600 by 400 (3:2), 3.6 KB. The same picture as PF's.
 * From Wikimedia Commons, "Flag of French Polynesia.svg" (CC0); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/fr-pf";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
