// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Wallis_and_Futuna.svg, the same drawing as WF's flag.

import { svg as shared } from "./wf";

/**
 * The flag of Wallis & Futuna (ウォリス・フツナ), FR-WF, as an SVG string: viewBox 150 by 100 (3:2), 391 B. The same picture as WF's.
 * From Wikimedia Commons, "Flag of Wallis and Futuna.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/fr-wf";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
