// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Kingdom_(3-5).svg, the same drawing as GB's flag.

import { svg as shared } from "./gb";

/**
 * The Union Flag: one of the flags of Northern Ireland (北アイルランド), GB-NIR, in real use, as an SVG string: viewBox 50 by 30 (5:3), 452 B. The same picture as GB's.
 * From Wikimedia Commons, "Flag of the United Kingdom (3-5).svg" (public domain). `flag("GB-NIR", { variant: "union-flag" })` loads it, and `variantsOf("GB-NIR")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/gb-nir--union-flag";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
