// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/gd.svg

/**
 * The flag of Grenada (グレナダ), GD, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 1.7 KB.
 * The drawing `flag("GD", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gd.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><g id=\"hata-gd-1x1-c\"><g id=\"hata-gd-1x1-b\"><path id=\"hata-gd-1x1-a\" fill=\"#fcd116\" d=\"M0-1v1h.5\" transform=\"rotate(18 0 -1)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-a\" transform=\"scale(-1 1)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-b\" transform=\"rotate(72)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-b\" transform=\"rotate(144)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-b\" transform=\"rotate(-144)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-b\" transform=\"rotate(-72)\"/></g></defs><path fill=\"#ce1126\" d=\"M0 0h512v512H0z\"/><path fill=\"#007a5e\" d=\"M71.7 71.7h368.6v368.6H71.7z\"/><path fill=\"#fcd116\" d=\"M71.7 71.7h368.6L71.7 440.4h368.6z\"/><circle cx=\"255.9\" cy=\"256.1\" r=\"61.4\" fill=\"#ce1126\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-c\" transform=\"translate(256 256)scale(56.32)\"/><use width=\"100%\" height=\"100%\" x=\"-100\" href=\"#hata-gd-1x1-d\" transform=\"translate(-16.4 -.1)\"/><use id=\"hata-gd-1x1-d\" width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-c\" transform=\"translate(256 35.9)scale(33.28)\"/><use width=\"100%\" height=\"100%\" x=\"100\" href=\"#hata-gd-1x1-d\" transform=\"translate(16.4)\"/><path fill=\"#ce1126\" d=\"M99.8 256.8c7.7 14.3 22.6 29.8 35.7 35.3.2-14.5-5-33.2-12-48z\"/><path fill=\"#fcd116\" d=\"M86.8 207.6c11.1 23.3-29 78.7 37.8 91.7a68 68 0 0 1-11.5-44.7 76 76 0 0 1 34.6 32.8c17.5-63.4-44.8-59.5-61-79.8z\"/><use width=\"100%\" height=\"100%\" x=\"-100\" href=\"#hata-gd-1x1-d\" transform=\"translate(-16.4 442)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-1x1-c\" transform=\"translate(256 478)scale(33.28)\"/><use width=\"100%\" height=\"100%\" x=\"100\" href=\"#hata-gd-1x1-d\" transform=\"translate(16.4 442.2)\"/></svg>";

export { svg };
export default svg;
