// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/gd.svg

/**
 * The flag of Grenada (グレナダ), GD, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 1.6 KB.
 * The drawing `flag("GD", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gd.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><g id=\"hata-gd-4x3-c\"><g id=\"hata-gd-4x3-b\"><path id=\"hata-gd-4x3-a\" fill=\"#fcd116\" d=\"M0-1v1h.5\" transform=\"rotate(18 0 -1)\"/><use href=\"#hata-gd-4x3-a\" transform=\"scale(-1 1)\"/></g><use href=\"#hata-gd-4x3-b\" transform=\"rotate(72)\"/><use href=\"#hata-gd-4x3-b\" transform=\"rotate(144)\"/><use href=\"#hata-gd-4x3-b\" transform=\"rotate(216)\"/><use href=\"#hata-gd-4x3-b\" transform=\"rotate(288)\"/></g></defs><path fill=\"#ce1126\" d=\"M0 0h640v480H0z\"/><path fill=\"#007a5e\" d=\"M67.2 67.2h505.6v345.6H67.2z\"/><path fill=\"#fcd116\" d=\"M67.2 67.3h505.6L67.2 412.9h505.6z\"/><circle cx=\"319.9\" cy=\"240.1\" r=\"57.6\" fill=\"#ce1126\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-4x3-c\" transform=\"translate(320 240)scale(52.8)\"/><use width=\"100%\" height=\"100%\" x=\"-100\" href=\"#hata-gd-4x3-d\" transform=\"translate(-30.3)\"/><use id=\"hata-gd-4x3-d\" width=\"100%\" height=\"100%\" href=\"#hata-gd-4x3-c\" transform=\"translate(320 33.6)scale(31.2)\"/><use width=\"100%\" height=\"100%\" x=\"100\" href=\"#hata-gd-4x3-d\" transform=\"translate(30.3)\"/><path fill=\"#ce1126\" d=\"M102.3 240.7a80 80 0 0 0 33.5 33.2 111 111 0 0 0-11.3-45z\"/><path fill=\"#fcd116\" d=\"M90.1 194.7c10.4 21.7-27.1 73.7 35.5 85.9a63 63 0 0 1-10.9-41.9 70 70 0 0 1 32.5 30.8c16.4-59.5-42-55.8-57.1-74.8\"/><use width=\"100%\" height=\"100%\" x=\"-100\" href=\"#hata-gd-4x3-d\" transform=\"translate(-30.3 414.6)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gd-4x3-c\" transform=\"translate(320 448.2)scale(31.2)\"/><use width=\"100%\" height=\"100%\" x=\"100\" href=\"#hata-gd-4x3-d\" transform=\"translate(30.3 414.6)\"/></svg>";

export { svg };
export default svg;
