// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Georgia.svg

/**
 * The flag of Georgia (ジョージア), GE, as an SVG string: viewBox 30 by 20 (3:2), 472 B.
 * From Wikimedia Commons, "Flag of Georgia.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ge";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"red\" viewBox=\"0 0 30 20\"><title>Flag of Georgia</title><path fill=\"#fff\" d=\"M0 0h30v20H0z\"/><path d=\"M13 0h4v20h-4zM0 8h30v4H0z\"/><g id=\"hata-ge-c\"><g id=\"hata-ge-b\"><path id=\"hata-ge-a\" d=\"M5.797 1.954a5.4 5.4 0 0 0 1.406 0 10.4 10.4 0 0 0 0 4.092 5.4 5.4 0 0 0-1.406 0 10.4 10.4 0 0 0 0-4.092\"/><use href=\"#hata-ge-a\" transform=\"rotate(90,6.5,4)\"/></g><use x=\"17\" href=\"#hata-ge-b\"/></g><use y=\"12\" href=\"#hata-ge-c\"/></svg>";

export { svg };
export default svg;
