// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_French_Guiana.svg

/**
 * French Guiana's local flag: one of the flags of French Guiana (仏領ギアナ), GF, in real use, as an SVG string: viewBox 900 by 600 (3:2), 249 B.
 * From Wikimedia Commons, "Flag of French Guiana.svg" (public domain). `flag("GF", { variant: "local" })` loads it, and `variantsOf("GF")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/gf--local";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = "<svg data-hata=\"gf--local\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#078930\" d=\"M0 0h900v600z\"/><path fill=\"#fcdd09\" d=\"m0 0 900 600H0z\"/><path fill=\"#da121a\" d=\"m450 200 58.8 180.9-153.9-111.8h190.2L391.2 380.9z\"/></svg>";

export { svg };
export default svg;
