// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/gg.svg

/**
 * The flag of Guernsey (ガーンジー), GG, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 537 B.
 * The drawing `flag("GG", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gg.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#fff\" d=\"M0 0h640v480H0z\"/><path fill=\"#e8112d\" d=\"M256 0h128v480H256z\"/><path fill=\"#e8112d\" d=\"M0 176h640v128H0z\"/><path id=\"hata-gg-4x3-a\" fill=\"#f9dd16\" d=\"m110 286.7 23.3-23.4h210v-46.6h-210L110 193.3z\"/><use width=\"36\" height=\"24\" href=\"#hata-gg-4x3-a\" transform=\"rotate(90 320 240)\"/><use width=\"36\" height=\"24\" href=\"#hata-gg-4x3-a\" transform=\"rotate(-90 320 240)\"/><use width=\"36\" height=\"24\" href=\"#hata-gg-4x3-a\" transform=\"rotate(180 320 240)\"/></svg>";

export { svg };
export default svg;
