// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/gh.svg

/**
 * The flag of Ghana (ガーナ), GH, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 256 B.
 * The drawing `flag("GH", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gh.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#006b3f\" d=\"M0 0h640v480H0z\"/><path fill=\"#fcd116\" d=\"M0 0h640v320H0z\"/><path fill=\"#ce1126\" d=\"M0 0h640v160H0z\"/><path fill=\"#000001\" d=\"m320 160 52 160-136-99h168l-136 99z\"/></svg>";

export { svg };
export default svg;
