// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Greenland.svg

/**
 * The flag of Greenland (グリーンランド), GL, as an SVG string: viewBox 18 by 12 (3:2), 189 B.
 * From Wikimedia Commons, "Flag of Greenland.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/gl";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"gl\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 18 12\"><path fill=\"#fff\" d=\"M0 0h18v12H0z\"/><path fill=\"#c8102e\" d=\"M0 6h18v6H0zm3 0a4 4 0 0 0 8 0 4 4 0 0 0-8 0\"/></svg>";

export { svg };
export default svg;
