// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/gm.svg

/**
 * The flag of Gambia (ガンビア), GM, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 486 B.
 * The drawing `flag("GM", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gm.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-gm-4x3-a\"><path fill-opacity=\".7\" d=\"M0-48h640v480H0z\"/></clipPath></defs><g fill-rule=\"evenodd\" stroke-width=\"1pt\" clip-path=\"url(#hata-gm-4x3-a)\" transform=\"translate(0 48)\"><path fill=\"red\" d=\"M0-128h640V85.3H0z\"/><path fill=\"#fff\" d=\"M0 85.3h640V121H0z\"/><path fill=\"#009\" d=\"M0 120.9h640V263H0z\"/><path fill=\"#fff\" d=\"M0 263.1h640v35.6H0z\"/><path fill=\"#090\" d=\"M0 298.7h640V512H0z\"/></g></svg>";

export { svg };
export default svg;
