// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/gr.svg

/**
 * The flag of Greece (ギリシャ), GR, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 794 B.
 * The drawing `flag("GR", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gr.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#0d5eaf\" fill-rule=\"evenodd\" d=\"M0 0h512v57H0z\"/><path fill=\"#fff\" fill-rule=\"evenodd\" d=\"M0 57h512v57H0z\"/><path fill=\"#0d5eaf\" fill-rule=\"evenodd\" d=\"M0 114h512v57H0z\"/><path fill=\"#fff\" fill-rule=\"evenodd\" d=\"M0 171h512v57H0z\"/><path fill=\"#0d5eaf\" fill-rule=\"evenodd\" d=\"M0 228h512v56.9H0z\"/><path fill=\"#fff\" fill-rule=\"evenodd\" d=\"M0 284.9h512v57H0z\"/><path fill=\"#0d5eaf\" fill-rule=\"evenodd\" d=\"M0 341.9h512v57H0z\"/><path fill=\"#fff\" fill-rule=\"evenodd\" d=\"M0 398.9h512v57H0z\"/><path fill=\"#0d5eaf\" d=\"M0 0h284.9v284.9H0z\"/><g fill=\"#fff\" fill-rule=\"evenodd\" stroke-width=\"1.3\"><path d=\"M114 0h57v284.9h-57z\"/><path d=\"M0 114h284.9v57H0z\"/></g><path fill=\"#0d5eaf\" fill-rule=\"evenodd\" d=\"M0 455h512v57H0z\"/></svg>";

export { svg };
export default svg;
