// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/gw.svg

/**
 * The flag of Guinea-Bissau (ギニアビサウ), GW, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 831 B.
 * The drawing `flag("GW", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/gw.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#ce1126\" d=\"M0 0h160v512H0z\"/><path fill=\"#fcd116\" d=\"M160 0h352v256H160z\"/><path fill=\"#009e49\" d=\"M160 256h352v256H160z\"/><g transform=\"translate(-46.2 72.8)scale(.7886)\"><g id=\"hata-gw-1x1-b\" transform=\"matrix(80 0 0 80 160 240)\"><path id=\"hata-gw-1x1-a\" fill=\"#000001\" d=\"M0-1v1h.5\" transform=\"rotate(18 0 -1)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gw-1x1-a\" transform=\"scale(-1 1)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-gw-1x1-b\" transform=\"rotate(72 160 240)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gw-1x1-b\" transform=\"rotate(144 160 240)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gw-1x1-b\" transform=\"rotate(-144 160 240)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-gw-1x1-b\" transform=\"rotate(-72 160 240)\"/></g></svg>";

export { svg };
export default svg;
