// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Australia_(converted).svg, the same drawing as AU's flag.

import { svg as shared } from "./au";

/**
 * The flag of Heard & McDonald Islands (ハード島・マクドナルド諸島), HM, as an SVG string: viewBox 10080 by 5040 (2:1), 1.2 KB. The same picture as AU's.
 * From Wikimedia Commons, "Flag of Australia (converted).svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/hm";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
