// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/hn.svg

/**
 * The flag of Honduras (ホンジュラス), HN, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 1.0 KB.
 * The drawing `flag("HN", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/hn.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#18c3df\" d=\"M0 0h640v480H0z\"/><path fill=\"#fff\" d=\"M0 160h640v160H0z\"/><g id=\"hata-hn-4x3-c\" fill=\"#18c3df\" transform=\"translate(320 240)scale(26.66665)\"><g id=\"hata-hn-4x3-b\"><path id=\"hata-hn-4x3-a\" d=\"m-.3 0 .5.1L0-1z\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-a\" transform=\"scale(-1 1)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-b\" transform=\"rotate(72)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-b\" transform=\"rotate(-72)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-b\" transform=\"rotate(144)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-b\" transform=\"rotate(-144)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-c\" transform=\"translate(133.3 -42.7)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-c\" transform=\"translate(133.3 37.3)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-c\" transform=\"translate(-133.3 -42.7)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-hn-4x3-c\" transform=\"translate(-133.3 37.3)\"/></svg>";

export { svg };
export default svg;
