// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Honduras_(1949%E2%80%932022,_2026%E2%80%93present).svg

/**
 * The flag of Honduras (ホンジュラス), HN, as an SVG string: viewBox 72 by 36 (2:1), 392 B.
 * From Wikimedia Commons, "Flag of Honduras (1949–2022, 2026–present).svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/hn";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"hn\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#0d3b99\" viewBox=\"0 0 72 36\"><title>Flag of Honduras</title><path fill=\"#fff\" d=\"M0 0h72v36H0z\"/><path d=\"M0 0h72v12H0zm0 24h72v12H0z\"/><g id=\"hata-hn-b\"><path id=\"hata-hn-a\" d=\"m26 13 1.18 3.62-3.08-2.24h3.8l-3.08 2.24z\"/><use y=\"6\" href=\"#hata-hn-a\"/></g><use x=\"10\" y=\"3\" href=\"#hata-hn-a\"/><use x=\"20\" href=\"#hata-hn-b\"/></svg>";

export { svg };
export default svg;
