// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Hungary.svg

/**
 * The flag of Hungary (ハンガリー), HU, as an SVG string: viewBox 1200 by 600 (2:1), 192 B.
 * From Wikimedia Commons, "Flag of Hungary.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/hu";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 600\"><path fill=\"#477050\" d=\"M0 0h1200v600H0\"/><path fill=\"#fff\" d=\"M0 0h1200v400H0\"/><path fill=\"#ce2939\" d=\"M0 0h1200v200H0\"/></svg>";

export { svg };
export default svg;
