// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Jamaica.svg

/**
 * The flag of Jamaica (ジャマイカ), JM, as an SVG string: viewBox 12 by 6 (2:1), 309 B.
 * From Wikimedia Commons, "Flag of Jamaica.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/jm";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"jm\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 12 6\"><title>Flag of Jamaica</title><defs><clipPath id=\"hata-jm-a\"><path d=\"M0 0h12v6H0z\"/></clipPath></defs><path fill=\"#007749\" d=\"M0 0h12v6H0z\"/><path fill=\"#2d2926\" stroke=\"#ffb81c\" d=\"M-2-1v8l16-8v8z\" clip-path=\"url(#hata-jm-a)\"/></svg>";

export { svg };
export default svg;
