// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/jo.svg

/**
 * The flag of Jordan (ヨルダン), JO, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 625 B.
 * The drawing `flag("JO", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/jo.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-jo-1x1-a\"><path fill-opacity=\".7\" d=\"M113.6 0H607v493.5H113.6z\"/></clipPath></defs><g clip-path=\"url(#hata-jo-1x1-a)\" transform=\"translate(-117.8)scale(1.0375)\"><g fill-rule=\"evenodd\" stroke-width=\"1pt\"><path fill=\"#000001\" d=\"M0 0h987v164.5H0z\"/><path fill=\"#fff\" d=\"M0 164.5h987V329H0z\"/><path fill=\"#090\" d=\"M0 329h987v164.5H0z\"/><path fill=\"red\" d=\"m0 493.5 493.5-246.8L0 0z\"/><path fill=\"#fff\" d=\"m164.8 244 22 10.6h-24.5l5.5 24-15.3-19.3-15.3 19.2 5.5-23.9H118l22.1-10.7-15.3-19.1 22.1 10.6 5.5-23.9 5.5 24 22-10.7z\"/></g></g></svg>";

export { svg };
export default svg;
