// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/jo.svg

/**
 * The flag of Jordan (ヨルダン), JO, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 650 B.
 * The drawing `flag("JO", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/jo.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-jo-4x3-a\"><path fill-opacity=\".7\" d=\"M-117.8 0h682.6v512h-682.6z\"/></clipPath></defs><g clip-path=\"url(#hata-jo-4x3-a)\" transform=\"translate(110.5)scale(.9375)\"><g fill-rule=\"evenodd\" stroke-width=\"1pt\"><path fill=\"#000001\" d=\"M-117.8 0h1024v170.7h-1024z\"/><path fill=\"#fff\" d=\"M-117.8 170.7h1024v170.6h-1024z\"/><path fill=\"#090\" d=\"M-117.8 341.3h1024V512h-1024z\"/><path fill=\"red\" d=\"m-117.8 512 512-256-512-256z\"/><path fill=\"#fff\" d=\"m24.5 289 5.7-24.9H4.7l23-11-15.9-19.9 23 11 5.6-24.8 5.7 24.9L69 233.2l-16 19.9 23 11H50.6l5.7 24.9-15.9-20z\"/></g></g></svg>";

export { svg };
export default svg;
