// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Nagano_Prefecture.svg

/**
 * The flag of Nagano (長野県), JP-20, as an SVG string: viewBox 900 by 600 (3:2), 272 B.
 * From Wikimedia Commons, "Flag of Nagano Prefecture.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/jp-20";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"jp-20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#f66637\" d=\"M0 0h900v600H0z\"/><circle cx=\"300\" cy=\"300\" r=\"250\" fill=\"#fff\"/><path fill=\"none\" stroke=\"#f66637\" stroke-width=\"50\" d=\"M10 300h600M150 25a275 275 0 0 1 0 550\"/></svg>";

export { svg };
export default svg;
