// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Wakayama_Prefecture.svg

/**
 * The flag of Wakayama (和歌山県), JP-30, as an SVG string: viewBox 90 by 60 (3:2), 221 B.
 * From Wikimedia Commons, "Flag of Wakayama Prefecture.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/jp-30";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"-45 -30 90 60\"><path fill=\"#fff\" d=\"M-45-30h90v60h-90z\"/><path fill=\"#29437f\" d=\"M-19.36 5a20 20 0 1 1 38.72 0L0 20l-8.91-6.9L8 0A8 8 0 0 0-8 0l7.33 5.68-8.91 6.9z\"/></svg>";

export { svg };
export default svg;
