// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Yamaguchi_Prefecture.svg

/**
 * The flag of Yamaguchi (山口県), JP-35, as an SVG string: viewBox 600 by 400 (3:2), 274 B.
 * From Wikimedia Commons, "Flag of Yamaguchi Prefecture.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/jp-35";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"jp-35\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"-300 -200 600 400\"><path fill=\"#693c34\" d=\"M-300-200h600v400h-600z\"/><path fill=\"#fff\" d=\"M-75.6 79.9a110 110 0 0 0 151.2 0l99.5-94.2h-66a110 110 0 0 0-218.2 0h-66zM0-11l-28.5 70.5a66 66 0 1 1 57 0z\"/></svg>";

export { svg };
export default svg;
