// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Shimane_Prefecture.svg

/**
 * The flag of Shimane (島根県), JP-32, as an SVG string: viewBox 150 by 100 (3:2), 350 B.
 * From Wikimedia Commons, "Flag of Shimane Prefecture.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/jp-32";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"-75 -50 150 100\"><path fill=\"#950017\" d=\"M-75-50H75V50H-75z\"/><g id=\"hata-jp-32-b\"><path id=\"hata-jp-32-a\" fill=\"gold\" d=\"m0 0 10-9a12 12 0 0 1 7.3-3v8a4 4 0 1 0 1.4 0v-8A12 12 0 1 1 6 0z\"/><use href=\"#hata-jp-32-a\" transform=\"rotate(180)\"/></g><use href=\"#hata-jp-32-b\" transform=\"rotate(90)\"/></svg>";

export { svg };
export default svg;
