// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Miyazaki_Prefecture.svg

/**
 * The flag of Miyazaki (宮崎県), JP-45, as an SVG string: viewBox 1400 by 1000 (7:5), 215 B.
 * From Wikimedia Commons, "Flag of Miyazaki Prefecture.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/jp-45";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1400 1000\"><path fill=\"#159939\" d=\"M0 0h1400v1000H0z\"/><path fill=\"#ffff01\" d=\"M312 215h392L575 405h380L825 595h402l-128 175H695l130-190H445l129-190H184z\"/></svg>";

export { svg };
export default svg;
