// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/jp.svg

/**
 * The flag of Japan (日本), JP, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 390 B.
 * The drawing `flag("JP", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/jp.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-jp-1x1-a\"><path d=\"M177 0h709v709H177z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-jp-1x1-a)\" transform=\"translate(-128)scale(.72249)\"><path fill=\"#fff\" d=\"M0 0h1063v709H0z\"/><circle cx=\"523\" cy=\"344\" r=\"195\" fill=\"#bc002d\" transform=\"translate(-59.7 -34.5)scale(1.1302)\"/></g></svg>";

export { svg };
export default svg;
