// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_Comoros.svg

/**
 * The flag of Comoros (コモロ), KM, as an SVG string: viewBox 60 by 36 (5:3), 557 B.
 * From Wikimedia Commons, "Flag of the Comoros.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/km";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"km\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#fff\" viewBox=\"0 0 60 36\"><title>Flag of the Comoros</title><path d=\"M0 0h60v36H0z\"/><path fill=\"#ffd100\" d=\"M0 0h60v9H0z\"/><path fill=\"#ef3340\" d=\"M0 18h60v18H0z\"/><path fill=\"#003da5\" d=\"M0 27h60v9H0z\"/><path fill=\"#009639\" d=\"M30 18 0 36V0z\"/><path d=\"M12.519 9.809a8.25 8.25 0 0 0 0 16.382 8.5 8.5 0 1 1 0-16.382\"/><g id=\"hata-km-b\"><path id=\"hata-km-a\" d=\"m12.519 10.75 1.029 3.166-2.693-1.957h3.329l-2.693 1.957z\"/><use y=\"3.75\" href=\"#hata-km-a\"/></g><use y=\"7.5\" href=\"#hata-km-b\"/></svg>";

export { svg };
export default svg;
