// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/kn.svg

/**
 * The flag of St. Kitts & Nevis (セントクリストファー・ネーヴィス), KN, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 739 B.
 * The drawing `flag("KN", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/kn.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-kn-4x3-a\"><path fill-opacity=\".7\" d=\"M-80.1 0h682.7v512H-80.1z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-kn-4x3-a)\" transform=\"translate(75.1)scale(.9375)\"><path fill=\"#ffe900\" d=\"M-107.8.2h737.6v511.3h-737.6z\"/><path fill=\"#35a100\" d=\"m-108.2.2.8 368.6L466.6 0z\"/><path fill=\"#c70000\" d=\"m630.7 511.5-1.4-383.2-579 383.5z\"/><path fill=\"#000001\" d=\"m-107.9 396.6.5 115.4 125.3-.2 611.7-410.1L629 1.4 505.2.2z\"/><path fill=\"#fff\" d=\"m380.4 156.6-9.8-42.2 33.3 27 38-24.6-17.4 41.3 33.4 27-44.2-1.5-17.3 41.3-9.9-42.2-44.1-1.5zm-275.2 179-9.9-42.3 33.3 27 38-24.6-17.4 41.3 33.4 27-44.1-1.5-17.4 41.3-9.8-42.2-44.1-1.5z\"/></g></svg>";

export { svg };
export default svg;
