// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/kr.svg

/**
 * The flag of South Korea (韓国), KR, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 877 B.
 * The drawing `flag("KR", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/kr.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-kr-4x3-a\"><path d=\"M-96 0h683v512H-96z\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-kr-4x3-a)\" transform=\"translate(89.8 .4)scale(.9375)\"><path fill=\"#fff\" d=\"M-96 0h683v512H-96Z\"/><g transform=\"rotate(-56.3 361.6 -101.3)scale(10.66667)\"><g id=\"hata-kr-4x3-c\"><path id=\"hata-kr-4x3-b\" fill=\"#000001\" d=\"M-6-26H6v2H-6Zm0 3H6v2H-6Zm0 3H6v2H-6Z\"/><use width=\"100%\" height=\"100%\" y=\"44\" href=\"#hata-kr-4x3-b\"/></g><path stroke=\"#fff\" d=\"M0 17v10\"/><path fill=\"#cd2e3a\" d=\"M0-12a12 12 0 0 1 0 24Z\"/><path fill=\"#0047a0\" d=\"M0-12a12 12 0 0 0 0 24A6 6 0 0 0 0 0Z\"/><circle cy=\"-6\" r=\"6\" fill=\"#cd2e3a\"/></g><g transform=\"rotate(-123.7 191.2 62.2)scale(10.66667)\"><use width=\"100%\" height=\"100%\" href=\"#hata-kr-4x3-c\"/><path stroke=\"#fff\" d=\"M0-23v3m0 37v4m0 3v3\"/></g></g></svg>";

export { svg };
export default svg;
