// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/lc.svg

/**
 * The flag of St. Lucia (セントルシア), LC, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 305 B.
 * The drawing `flag("LC", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/lc.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><g fill-rule=\"evenodd\"><path fill=\"#65cfff\" d=\"M0 0h640v480H0z\"/><path fill=\"#fff\" d=\"m318.9 42 162.7 395.3-322.6.9z\"/><path fill=\"#000001\" d=\"m319 96.5 140.8 340-279 .8z\"/><path fill=\"#ffce00\" d=\"m318.9 240.1 162.7 197.6-322.6.5z\"/></g></svg>";

export { svg };
export default svg;
