// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Liberia.svg

/**
 * The flag of Liberia (リベリア), LR, as an SVG string: viewBox 209 by 110 (19:10), 647 B.
 * From Wikimedia Commons, "Flag of Liberia.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/lr";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 209 110\"><path fill=\"#bf0a30\" d=\"M0 0h209v110H0z\"/><path stroke=\"#fff\" stroke-width=\"10\" d=\"M0 15h209m0 20H0\"/><path fill=\"#00205b\" d=\"M0 0h50v55H0z\"/><path stroke=\"#fff\" stroke-width=\"10\" d=\"M0 55h209m0 20H0m0 20h209\"/><g transform=\"translate(25,25) scale(15)\"><g id=\"hata-lr-b\"><path id=\"hata-lr-a\" fill=\"#fff\" d=\"M0 0v1h.5z\" transform=\"translate(0,-1) rotate(18)\"/><use href=\"#hata-lr-a\" transform=\"scale(-1,1)\"/></g><g id=\"hata-lr-c\"><use href=\"#hata-lr-b\" transform=\"rotate(72)\"/><use href=\"#hata-lr-b\" transform=\"rotate(216)\"/></g><use href=\"#hata-lr-c\" transform=\"rotate(72)\"/></g></svg>";

export { svg };
export default svg;
