// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Lithuania.svg

/**
 * The flag of Lithuania (リトアニア), LT, as an SVG string: viewBox 1000 by 600 (5:3), 198 B.
 * From Wikimedia Commons, "Flag of Lithuania.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/lt";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 600\"><path fill=\"#c1272d\" d=\"M0 0h1000v600H0z\"/><path fill=\"#006a44\" d=\"M0 0h1000v400H0z\"/><path fill=\"#fdb913\" d=\"M0 0h1000v200H0z\"/></svg>";

export { svg };
export default svg;
