// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Luxembourg.svg

/**
 * The flag of Luxembourg (ルクセンブルク), LU, as an SVG string: viewBox 5 by 3 (5:3), 175 B.
 * From Wikimedia Commons, "Flag of Luxembourg.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/lu";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 5 3\"><path fill=\"#ef3340\" d=\"M0 0h5v1H0Z\"/><path fill=\"#fff\" d=\"M0 1h5v1H0Z\"/><path fill=\"#00a3e0\" d=\"M0 2h5v1H0Z\"/></svg>";

export { svg };
export default svg;
