// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/ly.svg

/**
 * The flag of Libya (リビア), LY, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 495 B.
 * The drawing `flag("LY", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/ly.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-ly-1x1-a\"><path d=\"M250 12h500v500H250z\"/></clipPath></defs><g clip-path=\"url(#hata-ly-1x1-a)\" transform=\"translate(-256 -12.3)scale(1.024)\"><path fill=\"#239e46\" d=\"M0 12h1000v500H0z\"/><path fill=\"#000001\" d=\"M0 12h1000v375H0z\"/><path fill=\"#e70013\" d=\"M0 12h1000v125H0z\"/><path fill=\"#fff\" d=\"M544.2 217.8a54.3 54.3 0 1 0 0 88.4 62.5 62.5 0 1 1 0-88.4M530.4 262l84.1-27.3-52 71.5v-88.4l52 71.5z\"/></g></svg>";

export { svg };
export default svg;
