// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Morocco.svg

/**
 * The flag of Morocco (モロッコ), MA, as an SVG string: viewBox 90000 by 60000 (3:2), 233 B.
 * From Wikimedia Commons, "Flag of Morocco.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ma";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 90000 60000\"><path fill=\"#c1272d\" d=\"M0 0h90000v60000H0z\"/><path fill=\"none\" stroke=\"#006233\" stroke-width=\"1426\" d=\"m45000 17308 7460 22960-19531-14190h24142L37540 40268z\"/></svg>";

export { svg };
export default svg;
