// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/mg.svg

/**
 * The flag of Madagascar (マダガスカル), MG, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 257 B.
 * The drawing `flag("MG", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/mg.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><g fill-rule=\"evenodd\" stroke-width=\"1pt\"><path fill=\"#fc3d32\" d=\"M213.3 0H640v240H213.3z\"/><path fill=\"#007e3a\" d=\"M213.3 240H640v240H213.3z\"/><path fill=\"#fff\" d=\"M0 0h213.3v480H0z\"/></g></svg>";

export { svg };
export default svg;
