// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/mk.svg

/**
 * The flag of North Macedonia (北マケドニア), MK, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 336 B.
 * The drawing `flag("MK", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/mk.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#d20000\" d=\"M0 0h640v480H0z\"/><path fill=\"#ffe600\" d=\"M0 0h96l224 231L544 0h96L0 480h96l224-231 224 231h96zm640 192v96L0 192v96zM280 0l40 206L360 0zm0 480 40-206 40 206z\"/><circle cx=\"320\" cy=\"240\" r=\"77\" fill=\"#ffe600\" stroke=\"#d20000\" stroke-width=\"17\"/></svg>";

export { svg };
export default svg;
