// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Myanmar.svg

/**
 * The flag of Myanmar (Burma) (ミャンマー (ビルマ)), MM, as an SVG string: viewBox 18 by 12 (3:2), 486 B.
 * From Wikimedia Commons, "Flag of Myanmar.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/mm";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 18 12\"><path fill=\"#fecb00\" d=\"M0 0h18v12H0z\"/><path fill=\"#34b233\" d=\"M0 4h18v8H0z\"/><path fill=\"#ea2839\" d=\"M0 8h18v4H0z\"/><g transform=\"translate(9,6.422) scale(4.422)\"><path id=\"hata-mm-a\" fill=\"#fff\" d=\"M-.325 0 0-1l.325 1z\"/><use href=\"#hata-mm-a\" transform=\"rotate(-144)\"/><use href=\"#hata-mm-a\" transform=\"rotate(-72)\"/><use href=\"#hata-mm-a\" transform=\"rotate(72)\"/><use href=\"#hata-mm-a\" transform=\"rotate(144)\"/></g></svg>";

export { svg };
export default svg;
