// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/mq.svg

/**
 * The flag of Martinique (マルティニーク), MQ, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 196 B.
 * The drawing `flag("MQ", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/mq.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#231f1e\" d=\"M0 0h512v512H0z\"/><path fill=\"#00a650\" d=\"M0 0h512v256H0z\"/><path fill=\"#ef1923\" d=\"M256 256 0 512V0z\"/></svg>";

export { svg };
export default svg;
