// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/mv.svg

/**
 * The flag of Maldives (モルディブ), MV, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 271 B.
 * The drawing `flag("MV", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/mv.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#d21034\" d=\"M0 0h512v512H0z\"/><path fill=\"#007e3a\" d=\"M128 128h256v256H128z\"/><circle cx=\"288\" cy=\"256\" r=\"85.3\" fill=\"#fff\"/><ellipse cx=\"308.6\" cy=\"256\" fill=\"#007e3a\" rx=\"73.9\" ry=\"85.3\"/></svg>";

export { svg };
export default svg;
