// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Mozambique.svg

/**
 * The flag of Mozambique (モザンビーク), MZ, as an SVG string: viewBox 900 by 600 (3:2), 1.9 KB.
 * From Wikimedia Commons, "Flag of Mozambique.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/mz";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path d=\"M0 0h900v600H0z\"/><path fill=\"#fff\" d=\"M0 0h900v206.3H0z\"/><path fill=\"#007168\" d=\"M0 0h900v187.5H0z\"/><path fill=\"#fff\" d=\"M0 393.5h900V600H0z\"/><path fill=\"#fce100\" d=\"M0 412.5h900V600H0z\"/><path fill=\"#d21034\" d=\"M0 0v600l393.8-300z\"/><path fill=\"#fce100\" d=\"m204.4 412.5-73.2-53.6-73 53.6 28.3-86.1-73.5-53 90.6.4 27.6-86.3 27.7 86.3 90.6-.4-73.5 53z\"/><g stroke=\"#000\" stroke-linejoin=\"round\" stroke-width=\"1.6\"><path fill=\"#fff\" fill-rule=\"evenodd\" d=\"M67.7 352.4h52.7c4.3 4.8 13.7 6.7 22.7 0 16.6-9 48.5 0 48.5 0l6.3-6.7-15.3-50.3-5.5-5.9s-11.8-7-34.3-4.7-30.2-.8-30.2-.8-19.7 2.4-25.2 5.1l-6.3 6.3z\"/><g stroke-linecap=\"round\"><path fill=\"none\" d=\"M78.3 339.5s50.4-6.3 65 13c-8.3 5.6-15.5 6-23.3.3 1.3-2 18.1-19.6 61-13.7\"/><path d=\"m132.2 289.1-.4 55.5m45.3-54.7 9.4 44m-98.6-44.7-5.2 22.7\"/></g><path fill-rule=\"evenodd\" d=\"M33.5 358.5 45.9 373q2 1.3 4 0l18.4-22 7.7-9.6a6 6 0 0 0 1.5-4.4l14.7-13.1 3.2.3c-1.5-.4-2.5-1-1.4-2.6l3.3-2.6 2.6 3.3-4 4.8h-4l-7.8 7 3.4 3 5 13.9 6.3-4.5-4-14.3 8.8-9.5-3.3-5.2 2.2-3s30.5 19.3 42.2 14.2c.3 0 .7-13.7.7-13.7s-31.6-3.4-32.3-9.6 7-7 7-7l-3.3-4.8.7-2.5 5.5 7 12.5-10.7 73.5 83.8c4-1.7 4.9-2.6 5.1-6.7l-72-82.6 5.5-5.9c1.1-1.2 1.5-1.7 1.5-3.7l8.5-7.3q3.6 1.4 5.5 4.4l23.2-19.7c.6.6 2.5 1.2 3.7.6l38.4-37-41.8 29.7-1.5-1.1c0-1.3 1.5-1.6 0-3.7-1.6-2-4 1.8-4.4 1.8s-6-2-7.3-4.5l-.4 6.7-10.7 10-8-.4-11.8 11.4-1.5 4.4 1.9 3.6s-6.3 5.6-6.3 5.2-1.2-1.6-1.3-1.8l5.4-4.8.7-3.3-1.8-2.8c-.5.4-7.4 7.5-7.8 6.8L112 248.1l1.1-4-12.5-13.6c-4.5-1.6-11.7-1.9-13.2 8-1.1 2.4-10.7.4-10.7.4l-5.1 1.1-29 41.2 16.1 19.4 33.1-41.8 1-12 7 7.8c2.2.3 4.4.4 6.5-.7l19.6 21.9-3.2 3.2 3 3.2 3.2-2.4 1.3 2-4.4 3c-2.6-1.8-5.2-4-5-7.3l-11 9.2-.4 1.8-32.7 27.2-2.9.4-.7 8.4L94.4 307v-2.6l2.2 1.8L113 293s1.1 1.5.7 1.5-14.6 13.2-14.6 13.2l-.4 1.5-2.6 2.2-1.5-1.1L75 327.8h-3l-11 11a16 16 0 0 0-7.7 2.2z\"/></g></svg>";

export { svg };
export default svg;
