// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_France.svg, the same drawing as FR's flag.

import { svg as shared } from "./fr";

/**
 * France's flag: one of the flags of New Caledonia (ニューカレドニア), NC, in real use, as an SVG string: viewBox 900 by 600 (3:2), 203 B. The same picture as FR's.
 * From Wikimedia Commons, "Flag of France.svg" (public domain). `flag("NC", { variant: "france" })` loads it, and `variantsOf("NC")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/nc--france";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
