// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_New_Zealand.svg

/**
 * The flag of New Zealand (ニュージーランド), NZ, as an SVG string: viewBox 1200 by 600 (2:1), 1.7 KB.
 * From Wikimedia Commons, "Flag of New Zealand.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/nz";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 600\"><defs><clipPath id=\"hata-nz-b\"><path d=\"M0 0h600v300H0z\"/></clipPath><clipPath id=\"hata-nz-c\"><path d=\"m0 0 300 150H0zm300 0h300L300 150zm0 150h300v150zm0 0v150H0z\"/></clipPath><g id=\"hata-nz-d\"><g id=\"hata-nz-a\"><path d=\"M0-.32v.5l1-.5z\"/><path d=\"m.2.26-.3-.4L1-.32z\"/></g><use href=\"#hata-nz-a\" transform=\"scale(-1,1)\"/><use href=\"#hata-nz-a\" transform=\"rotate(72,0,0)\"/><use href=\"#hata-nz-a\" transform=\"rotate(-72,0,0)\"/><use href=\"#hata-nz-a\" transform=\"rotate(-72,0,0) scale(-1,1)\"/></g></defs><path fill=\"#012169\" d=\"M0 0h1200v600H0z\"/><path stroke=\"#fff\" stroke-width=\"60\" d=\"m0 0 600 300M0 300 600 0\" clip-path=\"url(#hata-nz-b)\"/><path stroke=\"#c8102e\" stroke-width=\"40\" d=\"m0 0 600 300M0 300 600 0\" clip-path=\"url(#hata-nz-c)\"/><path stroke=\"#fff\" stroke-width=\"100\" d=\"M300 0v300M0 150h600\" clip-path=\"url(#hata-nz-b)\"/><path stroke=\"#c8102e\" stroke-width=\"60\" d=\"M300 0v300M0 150h600\" clip-path=\"url(#hata-nz-b)\"/><use fill=\"#fff\" href=\"#hata-nz-d\" transform=\"translate(900,120) scale(45.4)\"/><use fill=\"#c8102e\" href=\"#hata-nz-d\" transform=\"translate(900,120) scale(30)\"/><g transform=\"rotate(82,900,240)\"><use fill=\"#fff\" href=\"#hata-nz-d\" transform=\"translate(900,120) rotate(-82) scale(40.4)\"/><use fill=\"#c8102e\" href=\"#hata-nz-d\" transform=\"translate(900,120) rotate(-82) scale(25)\"/></g><g transform=\"rotate(82,900,240)\"><use fill=\"#fff\" href=\"#hata-nz-d\" transform=\"translate(900,380) rotate(-82) scale(45.4)\"/><use fill=\"#c8102e\" href=\"#hata-nz-d\" transform=\"translate(900,380) rotate(-82) scale(30)\"/></g><use fill=\"#fff\" href=\"#hata-nz-d\" transform=\"translate(900,480) scale(50.4)\"/><use fill=\"#c8102e\" href=\"#hata-nz-d\" transform=\"translate(900,480) scale(35)\"/></svg>";

export { svg };
export default svg;
