// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Poland.svg

/**
 * The flag of Poland (ポーランド), PL, as an SVG string: viewBox 8 by 5 (8:5), 139 B.
 * From Wikimedia Commons, "Flag of Poland.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/pl";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 8 5\"><path fill=\"#dc143c\" d=\"M0 0h8v5H0z\"/><path fill=\"#fff\" d=\"M0 0h8v2.5H0z\"/></svg>";

export { svg };
export default svg;
