// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Palestine.svg

/**
 * The flag of Palestinian Territories (パレスチナ自治区), PS, as an SVG string: viewBox 6 by 3 (2:1), 217 B.
 * From Wikimedia Commons, "Flag of Palestine.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/ps";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"ps\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 6 3\"><path fill=\"#009639\" d=\"M0 0h6v3H0z\"/><path fill=\"#fff\" d=\"M0 0h6v2H0z\"/><path d=\"M0 0h6v1H0z\"/><path fill=\"#ed2e38\" d=\"m0 0 2 1.5L0 3Z\"/></svg>";

export { svg };
export default svg;
