// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/pw.svg

/**
 * The flag of Palau (パラオ), PW, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 424 B.
 * The drawing `flag("PW", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/pw.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-pw-4x3-a\"><path fill-opacity=\".7\" d=\"M-70.3 0h640v480h-640z\"/></clipPath></defs><g fill-rule=\"evenodd\" stroke-width=\"1pt\" clip-path=\"url(#hata-pw-4x3-a)\" transform=\"translate(70.3)\"><path fill=\"#4aadd6\" d=\"M-173.4 0h846.3v480h-846.3z\"/><path fill=\"#ffde00\" d=\"M335.6 232.1a135.9 130.1 0 1 1-271.7 0 135.9 130.1 0 1 1 271.7 0\"/></g></svg>";

export { svg };
export default svg;
