// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Qatar.svg

/**
 * The flag of Qatar (カタール), QA, as an SVG string: viewBox 75 by 18 (4.167:1), 211 B.
 * From Wikimedia Commons, "Flag of Qatar.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/qa";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 75 18\"><path fill=\"#8a1538\" d=\"M0 0h75v18H0\"/><path fill=\"#fff\" d=\"M22 18H0V0h22l6 1-6 1 6 1-6 1 6 1-6 1 6 1-6 1 6 1-6 1 6 1-6 1 6 1-6 1 6 1-6 1 6 1z\"/></svg>";

export { svg };
export default svg;
