// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Proposed_flag_of_R%C3%A9union_(VAR).svg

/**
 * The Lofo: one of the flags of Réunion (レユニオン), RE, in real use, as an SVG string: viewBox 120 by 80 (3:2), 277 B.
 * From Wikimedia Commons, "Proposed flag of Réunion (VAR).svg" (public domain). `flag("RE", { variant: "local" })` loads it, and `variantsOf("RE")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/re--local";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = "<svg data-hata=\"re--local\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 120 80\"><path fill=\"#36f\" d=\"M0 0h120v80H0z\"/><path fill=\"red\" d=\"M60 40 0 80h120z\"/><g fill=\"#ff0\"><path d=\"M0 37v6l120-6v6z\"/><path d=\"M60 40 0 5V0h5zl55-40h5v5z\"/><path d=\"M60 40 57 0h6z\"/></g></svg>";

export { svg };
export default svg;
