// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/rw.svg

/**
 * The flag of Rwanda (ルワンダ), RW, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 667 B.
 * The drawing `flag("RW", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/rw.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#20603d\" d=\"M0 0h512v512H0z\"/><path fill=\"#fad201\" d=\"M0 0h512v384H0z\"/><path fill=\"#00a1de\" d=\"M0 0h512v256H0z\"/><g transform=\"translate(374.4 133.8)scale(.7111)\"><g id=\"hata-rw-1x1-b\"><path id=\"hata-rw-1x1-a\" fill=\"#e5be01\" d=\"M116.1 0 35.7 4.7l76.4 25.4-78.8-16.3L100.6 58l-72-36.2L82 82.1 21.9 28.6l36.2 72-44.3-67.3L30 112 4.7 35.7 0 116.1-1-1z\"/><use width=\"100%\" height=\"100%\" href=\"#hata-rw-1x1-a\" transform=\"scale(1 -1)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-rw-1x1-b\" transform=\"scale(-1 1)\"/><circle r=\"34.3\" fill=\"#e5be01\" stroke=\"#00a1de\" stroke-width=\"3.4\"/></g></svg>";

export { svg };
export default svg;
