// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/sc.svg

/**
 * The flag of Seychelles (セーシェル), SC, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 285 B.
 * The drawing `flag("SC", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/sc.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#fff\" d=\"M0 0h512v512H0Z\"/><path fill=\"#d92223\" d=\"M0 512V0h512v170.7z\"/><path fill=\"#fcd955\" d=\"M0 512V0h341.3z\"/><path fill=\"#003d88\" d=\"M0 512V0h170.7z\"/><path fill=\"#007a39\" d=\"m0 512 512-170.7V512Z\"/></svg>";

export { svg };
export default svg;
