// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/sd.svg

/**
 * The flag of Sudan (スーダン), SD, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 455 B.
 * The drawing `flag("SD", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/sd.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-sd-1x1-a\"><path fill-opacity=\".7\" d=\"M0 0h496v496H0z\"/></clipPath></defs><g fill-rule=\"evenodd\" stroke-width=\"1pt\" clip-path=\"url(#hata-sd-1x1-a)\" transform=\"scale(1.0321)\"><path fill=\"#000001\" d=\"M0 330.7h992.1v165.4H0z\"/><path fill=\"#fff\" d=\"M0 165.3h992.1v165.4H0z\"/><path fill=\"red\" d=\"M0 0h992.9v165.4H0z\"/><path fill=\"#009a00\" d=\"M0 0v496l330.7-248z\"/></g></svg>";

export { svg };
export default svg;
