// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Sudan.svg

/**
 * The flag of Sudan (スーダン), SD, as an SVG string: viewBox 1200 by 600 (2:1), 226 B.
 * From Wikimedia Commons, "Flag of Sudan.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/sd";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 600\"><path d=\"M0 0h1200v600H0z\"/><path fill=\"#fff\" d=\"M0 0h1200v400H0z\"/><path fill=\"#d21034\" d=\"M0 0h1200v200H0z\"/><path fill=\"#007229\" d=\"m0 0 400 300L0 600z\"/></svg>";

export { svg };
export default svg;
