// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Norway.svg, the same drawing as NO's flag.

import { svg as shared } from "./no";

/**
 * The flag of Svalbard & Jan Mayen (スバールバル諸島・ヤンマイエン島), SJ, as an SVG string: viewBox 22 by 16 (11:8), 252 B. The same picture as NO's.
 * From Wikimedia Commons, "Flag of Norway.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/sj";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
