// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/sl.svg

/**
 * The flag of Sierra Leone (シエラレオネ), SL, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 394 B.
 * The drawing `flag("SL", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/sl.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><clipPath id=\"hata-sl-1x1-a\"><rect width=\"384\" height=\"512\" rx=\"4.6\" ry=\"7.6\"/></clipPath></defs><g fill-rule=\"evenodd\" clip-path=\"url(#hata-sl-1x1-a)\" transform=\"scale(1.33333 1)\"><path fill=\"#0000cd\" d=\"M0 341.7h512V512H0z\"/><path fill=\"#fff\" d=\"M0 171.4h512v170.3H0z\"/><path fill=\"#00cd00\" d=\"M0 0h512v171.4H0z\"/></g></svg>";

export { svg };
export default svg;
