// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Senegal.svg

/**
 * The flag of Senegal (セネガル), SN, as an SVG string: viewBox 900 by 600 (3:2), 240 B.
 * From Wikimedia Commons, "Flag of Senegal.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/sn";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"sn\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#e31b23\" d=\"M0 0h900v600H0\"/><path fill=\"#fdef42\" d=\"M0 0h600v600H0\"/><path fill=\"#00853f\" d=\"M0 0h300v600H0m391-218 59-181 59 181-154-112h190\"/></svg>";

export { svg };
export default svg;
