// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Suriname.svg

/**
 * The flag of Suriname (スリナム), SR, as an SVG string: viewBox 900 by 600 (3:2), 273 B.
 * From Wikimedia Commons, "Flag of Suriname.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/sr";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"sr\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#377e3f\" d=\"M0 0h900v600H0z\"/><path fill=\"#fff\" d=\"M0 120h900v360H0z\"/><path fill=\"#b40a2d\" d=\"M0 180h900v240H0z\"/><path fill=\"#ecc81d\" d=\"m450 191 71 218-185-135h228L379 409z\"/></svg>";

export { svg };
export default svg;
