// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/ss.svg

/**
 * The flag of South Sudan (南スーダン), SS, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 346 B.
 * The drawing `flag("SS", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/ss.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#078930\" d=\"M0 336h640v144H0z\"/><path fill=\"#fff\" d=\"M0 144h640v192H0z\"/><path fill=\"#000001\" d=\"M0 0h640v144H0z\"/><path fill=\"#da121a\" d=\"M0 168h640v144H0z\"/><path fill=\"#0f47af\" d=\"m0 0 416 240L0 480z\"/><path fill=\"#fcdd09\" d=\"M201 195 62 240l139 45-86-118v146z\"/></svg>";

export { svg };
export default svg;
