// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Arab_Republic_(1958%E2%80%931971),_Flag_of_Syria_(1980%E2%80%932024).svg

/**
 * The red, white and black flag: one of the flags of Syria (シリア), SY, in real use, as an SVG string: viewBox 900 by 600 (3:2), 334 B.
 * From Wikimedia Commons, "Flag of Syria (1980–2024).svg" (public domain). `flag("SY", { variant: "assad-era" })` loads it, and `variantsOf("SY")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/sy--assad-era";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = "<svg data-hata=\"sy--assad-era\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path d=\"M0 0h900v600H0z\"/><path fill=\"#fff\" d=\"M0 0h900v400H0z\"/><path fill=\"#ce1126\" d=\"M0 0h900v200H0z\"/><path fill=\"#007a3d\" d=\"m251.266 375 48.738-150 48.738 150-127.6-92.705h157.72M551.262 375 600 225l48.738 150-127.6-92.705h157.72\"/></svg>";

export { svg };
export default svg;
