// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/td.svg

/**
 * The flag of Chad (チャド), TD, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 241 B.
 * The drawing `flag("TD", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/td.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><g fill-rule=\"evenodd\"><path fill=\"#002664\" d=\"M0 0h171.2v512H0z\"/><path fill=\"#c60c30\" d=\"M340.8 0H512v512H340.8z\"/><path fill=\"#fecb00\" d=\"M171.2 0h169.6v512H171.2z\"/></g></svg>";

export { svg };
export default svg;
