// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Chad.svg

/**
 * The flag of Chad (チャド), TD, as an SVG string: viewBox 900 by 600 (3:2), 209 B.
 * From Wikimedia Commons, "Flag of Chad.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/td";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"td\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#c60c30\" d=\"M0 0h900v600H0z\"/><path fill=\"#fecb00\" d=\"M0 0h600v600H0z\"/><path fill=\"#002664\" d=\"M0 0h300v600H0z\"/></svg>";

export { svg };
export default svg;
