// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/tf.svg

/**
 * The flag of French Southern Territories (仏領極南諸島), TF, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 1.1 KB.
 * The drawing `flag("TF", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/tf.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><path id=\"hata-tf-1x1-a\" fill=\"#fff\" d=\"m0-21 12.3 38L-20-6.5h40L-12.3 17z\"/></defs><path fill=\"#002395\" d=\"M0 0h512v512H0z\"/><path fill=\"#fff\" d=\"M0 0h312.3v210H0z\"/><path fill=\"#002395\" d=\"M0 0h102.4v204.8H0z\"/><path fill=\"#ed2939\" d=\"M204.8 0h102.4v204.8H204.8z\"/><path fill=\"#fff\" d=\"m282.4 234.2 16.5 26.3h46.9V352l-35.3-55-47.3 75.5h23l24.4-43.5 49.9 89.6 49.9-89.6 24.3 43.5h23L410.5 297l-35.2 55v-50.6h21.1l15.7-25h-36.8v-16h46.9l16.5-26.2zm55 112h-51.2v18h51.2zm97.3 0h-51.2v18h51.2z\"/><use width=\"100%\" height=\"100%\" x=\"416\" y=\"362\" href=\"#hata-tf-1x1-a\" transform=\"translate(-172)scale(1.28)\"/><use width=\"100%\" height=\"100%\" x=\"371\" y=\"328\" href=\"#hata-tf-1x1-a\" transform=\"translate(-172)scale(1.28)\"/><use width=\"100%\" height=\"100%\" x=\"461\" y=\"328\" href=\"#hata-tf-1x1-a\" transform=\"translate(-172)scale(1.28)\"/><use width=\"100%\" height=\"100%\" x=\"333\" y=\"227\" href=\"#hata-tf-1x1-a\" transform=\"translate(-172)scale(1.28)\"/><use width=\"100%\" height=\"100%\" x=\"499\" y=\"227\" href=\"#hata-tf-1x1-a\" transform=\"translate(-172)scale(1.28)\"/></svg>";

export { svg };
export default svg;
