// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/th.svg

/**
 * The flag of Thailand (タイ), TH, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 243 B.
 * The drawing `flag("TH", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/th.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><g fill-rule=\"evenodd\"><path fill=\"#f4f5f8\" d=\"M0 0h512v512H0z\"/><path fill=\"#2d2a4a\" d=\"M0 173.4h512V344H0z\"/><path fill=\"#a51931\" d=\"M0 0h512v88H0zm0 426.7h512V512H0z\"/></g></svg>";

export { svg };
export default svg;
