// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Thailand.svg

/**
 * The flag of Thailand (タイ), TH, as an SVG string: viewBox 900 by 600 (3:2), 198 B.
 * From Wikimedia Commons, "Flag of Thailand.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/th";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\"><path fill=\"#a51931\" d=\"M0 0h900v600H0z\"/><path fill=\"#f4f5f8\" d=\"M0 100h900v400H0z\"/><path fill=\"#2d2a4a\" d=\"M0 200h900v200H0z\"/></svg>";

export { svg };
export default svg;
