// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_East_Timor.svg

/**
 * The flag of Timor-Leste (東ティモール), TL, as an SVG string: viewBox 36 by 18 (2:1), 265 B.
 * From Wikimedia Commons, "Flag of East Timor.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/tl";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 36 18\"><title>Flag of Timor-Leste</title><path fill=\"#da291c\" d=\"M0 0h36v18H0z\"/><path fill=\"#ffc72c\" d=\"M18 9 0 18V0z\"/><path d=\"M12 9 0 18V0z\"/><path fill=\"#fff\" d=\"m2.8 6.3 3.8 4.2L1 9.3 6.2 7l-2.8 5z\"/></svg>";

export { svg };
export default svg;
