// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/to.svg

/**
 * The flag of Tonga (トンガ), TO, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 297 B.
 * The drawing `flag("TO", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/to.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><g fill-rule=\"evenodd\" stroke-width=\"1pt\"><path fill=\"#c10000\" d=\"M0 0h512v512H0z\"/><path fill=\"#fff\" d=\"M0 0h218.3v175H0z\"/><g fill=\"#c10000\"><path d=\"M89.8 27.3h34.8v121.9H89.8z\"/><path d=\"M168.2 70.8v34.8H46.3V70.8z\"/></g></g></svg>";

export { svg };
export default svg;
