// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Tonga.svg

/**
 * The flag of Tonga (トンガ), TO, as an SVG string: viewBox 96 by 48 (2:1), 202 B.
 * From Wikimedia Commons, "Flag of Tonga.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/to";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 96 48\"><g fill=\"#c10000\"><path d=\"M0 0h96v48H0z\"/><path fill=\"#fff\" d=\"M0 0h40v24H0z\"/><path d=\"M17 3h6v18h-6z\"/><path d=\"M11 9h18v6H11z\"/></g></svg>";

export { svg };
export default svg;
