// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Turkey.svg

/**
 * The flag of Türkiye (トルコ), TR, as an SVG string: viewBox 90000 by 60000 (3:2), 289 B.
 * From Wikimedia Commons, "Flag of Turkey.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/tr";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 -30000 90000 60000\"><title>Flag of Turkey</title><path fill=\"#e30a17\" d=\"M0-30000h90000v60000H0z\"/><path fill=\"#fff\" d=\"m41750 0 13568-4408-8386 11541V-7133l8386 11541zm925 8021a15000 15000 0 1 1 0-16042 12000 12000 0 1 0 0 16042\"/></svg>";

export { svg };
export default svg;
