// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/tt.svg

/**
 * The flag of Trinidad & Tobago (トリニダード・トバゴ), TT, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 274 B.
 * The drawing `flag("TT", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/tt.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#fff\" d=\"M0 0h640v480H0z\"/><path fill=\"#e00000\" fill-rule=\"evenodd\" d=\"M463.7 480 0 1v478.8zM176.3 0 640 479V.2z\"/><path fill=\"#000001\" fill-rule=\"evenodd\" d=\"M27.7.2h118.6l468.2 479.3H492.2z\"/></svg>";

export { svg };
export default svg;
