// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_Republic_of_China.svg

/**
 * The flag of Taiwan (台湾), TW, as an SVG string: viewBox 120 by 80 (3:2), 411 B.
 * From Wikimedia Commons, "Flag of the Republic of China.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/tw";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"tw\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 120 80\"><path fill=\"#fe0000\" d=\"M0 0h120v80H0z\"/><path fill=\"#000094\" d=\"M0 0h60v40H0z\"/><path id=\"hata-tw-a\" fill=\"#fff\" d=\"m30 5 4 15-4 15-4-15zM15 20l15 4 15-4-15-4z\"/><use href=\"#hata-tw-a\" transform=\"rotate(30,30,20)\"/><use href=\"#hata-tw-a\" transform=\"rotate(60,30,20)\"/><circle cx=\"30\" cy=\"20\" r=\"8\" fill=\"#fff\" stroke=\"#000094\"/></svg>";

export { svg };
export default svg;
