// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/tz.svg

/**
 * The flag of Tanzania (タンザニア), TZ, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 496 B.
 * The drawing `flag("TZ", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/tz.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><clipPath id=\"hata-tz-4x3-a\"><path fill-opacity=\".7\" d=\"M10 0h160v120H10z\"/></clipPath></defs><g fill-rule=\"evenodd\" stroke-width=\"1pt\" clip-path=\"url(#hata-tz-4x3-a)\" transform=\"matrix(4 0 0 4 -40 0)\"><path fill=\"#09f\" d=\"M0 0h180v120H0z\"/><path fill=\"#090\" d=\"M0 0h180L0 120z\"/><path fill=\"#000001\" d=\"M0 120h40l140-95V0h-40L0 95z\"/><path fill=\"#ff0\" d=\"M0 91.5 137.2 0h13.5L0 100.5zM29.3 120 180 19.5v9L42.8 120z\"/></g></svg>";

export { svg };
export default svg;
