// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Tanzania.svg

/**
 * The flag of Tanzania (タンザニア), TZ, as an SVG string: viewBox 72 by 48 (3:2), 284 B.
 * From Wikimedia Commons, "Flag of Tanzania.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/tz";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 72 48\"><title>Flag of Tanzania</title><path fill=\"#1eb53a\" d=\"M0 48V0h72z\"/><path fill=\"#00a3dd\" d=\"M72 0v48H0z\"/><path stroke=\"#fcd116\" stroke-width=\"19\" d=\"M0 48 72 0\"/><path stroke=\"#000\" stroke-width=\"13\" d=\"M0 48 72 0\"/></svg>";

export { svg };
export default svg;
