// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Alabama.svg

/**
 * The flag of Alabama (アラバマ州), US-AL, as an SVG string: viewBox 600 by 400 (3:2), 196 B.
 * From Wikimedia Commons, "Flag of Alabama.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-al";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"us-al\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 600 400\"><path fill=\"#fff\" d=\"M0 0h600v400H0z\"/><path stroke=\"#b10021\" stroke-width=\"68\" d=\"m0 0 600 400M0 400 600 0\"/></svg>";

export { svg };
export default svg;
