// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Guam.svg, the same drawing as GU's flag.

import { svg as shared } from "./gu";

/**
 * The flag of Guam (グアム), US-GU, as an SVG string: viewBox 738 by 396 (1.864:1), 6.8 KB. The same picture as GU's.
 * From Wikimedia Commons, "Flag of Guam.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-gu";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
