// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Hawaii.svg

/**
 * The flag of Hawaii (ハワイ州), US-HI, as an SVG string: viewBox 48 by 24 (2:1), 693 B.
 * From Wikimedia Commons, "Flag of Hawaii.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-hi";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"#012169\" viewBox=\"0 0 48 24\"><clipPath id=\"hata-us-hi-a\"><path d=\"M0 0h24v14H0z\"/></clipPath><clipPath id=\"hata-us-hi-b\"><path d=\"M0 0v6h22v6h-1zm21 0H10.5v13H0v-1z\"/></clipPath><path d=\"M0 0h48v24H0z\"/><path stroke=\"#fff\" stroke-width=\"2.4\" d=\"m0 0 28 16M21 0 0 12\" clip-path=\"url(#hata-us-hi-a)\"/><path stroke=\"#c8102e\" stroke-width=\"1.6\" d=\"m0 0 28 16M21 0 0 12\" clip-path=\"url(#hata-us-hi-b)\"/><path stroke=\"#fff\" stroke-width=\"4\" d=\"M10.5 0v14M0 6h24\"/><path fill=\"#fff\" d=\"M48 0v4H22l-1-1V0zm0 9v4H21V9zm0 9v6H0v-6z\"/><path fill=\"#c8102e\" d=\"M48 3v4.2H0V4.8h21V3zm0 9v3H0v-3zm0 9v3H0v-3zM9.3 0h2.4v13H9.3z\"/><path d=\"M48 6v2.5H21V6z\"/></svg>";

export { svg };
export default svg;
