// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_Northern_Mariana_Islands.svg, the same drawing as MP's flag.

import { svg as shared } from "./mp";

/**
 * The flag of Northern Mariana Islands (北マリアナ諸島), US-MP, as an SVG string: viewBox 291.04 by 145.52 (2:1), 130.0 KB. The same picture as MP's.
 * From Wikimedia Commons, "Flag of the Northern Mariana Islands.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-mp";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
