// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Tennessee.svg

/**
 * The flag of Tennessee (テネシー州), US-TN, as an SVG string: viewBox 240 by 144 (5:3), 880 B.
 * From Wikimedia Commons, "Flag of Tennessee.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-tn";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"us-tn\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 144\"><path fill=\"#c00\" d=\"M0 0h240v144H0z\"/><path fill=\"#fff\" d=\"M222 0h18v144h-18z\"/><path fill=\"#002d65\" d=\"M225 0h15v144h-15z\"/><path fill=\"#002d65\" d=\"M225 0h15v144h-15z\"/><g transform=\"translate(111,72)\"><circle r=\"39\" fill=\"#fff\"/><circle r=\"36\" fill=\"#002d65\"/><g id=\"hata-us-tn-c\" fill=\"#fff\" transform=\"rotate(18) translate(0,18.5)\"><g id=\"hata-us-tn-b\"><path id=\"hata-us-tn-a\" d=\"M0-17V0h9\" transform=\"rotate(18 0,-17)\"/><use href=\"#hata-us-tn-a\" transform=\"scale(-1,1)\"/></g><use href=\"#hata-us-tn-b\" transform=\"rotate(72)\"/><use href=\"#hata-us-tn-b\" transform=\"rotate(144)\"/><use href=\"#hata-us-tn-b\" transform=\"rotate(216)\"/><use href=\"#hata-us-tn-b\" transform=\"rotate(288)\"/></g><use href=\"#hata-us-tn-c\" transform=\"rotate(120)\"/><use href=\"#hata-us-tn-c\" transform=\"rotate(240)\"/></g></svg>";

export { svg };
export default svg;
