// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg, the same drawing as UM's flag.

import { svg as shared } from "./um";

/**
 * The flag of U.S. Outlying Islands (合衆国領有小離島), US-UM, as an SVG string: viewBox 7410 by 3900 (19:10), 727 B. The same picture as UM's.
 * From Wikimedia Commons, "Flag of the United States.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-um";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
