// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States_Virgin_Islands.svg, the same drawing as VI's flag.

import { svg as shared } from "./vi";

/**
 * The flag of U.S. Virgin Islands (米領ヴァージン諸島), US-VI, as an SVG string: viewBox 1275 by 850 (3:2), 14.0 KB. The same picture as VI's.
 * From Wikimedia Commons, "Flag of the United States Virgin Islands.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/us-vi";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = shared;

export { svg };
export default svg;
