// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/1x1/uz.svg

/**
 * The flag of Uzbekistan (ウズベキスタン), UZ, drawn again by hand at 1:1 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 512 by 512, 1.3 KB.
 * The drawing `flag("UZ", { shape: "1:1" })` uses (and the round frame, in a circle), made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/uz.1x1";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"#1eb53a\" d=\"M0 341.3h512V512H0z\"/><path fill=\"#0099b5\" d=\"M0 0h512v170.7H0z\"/><path fill=\"#ce1126\" d=\"M0 163.8h512v184.4H0z\"/><path fill=\"#fff\" d=\"M0 174h512v164H0z\"/><circle cx=\"143.4\" cy=\"81.9\" r=\"61.4\" fill=\"#fff\"/><circle cx=\"163.8\" cy=\"81.9\" r=\"61.4\" fill=\"#0099b5\"/><g fill=\"#fff\" transform=\"translate(278.5 131)scale(2.048)\"><g id=\"hata-uz-1x1-e\"><g id=\"hata-uz-1x1-d\"><g id=\"hata-uz-1x1-c\"><g id=\"hata-uz-1x1-b\"><path id=\"hata-uz-1x1-a\" d=\"M0-6-1.9-.3 1 .7\"/><use width=\"100%\" height=\"100%\" href=\"#hata-uz-1x1-a\" transform=\"scale(-1 1)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-uz-1x1-b\" transform=\"rotate(72)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-uz-1x1-b\" transform=\"rotate(-72)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-uz-1x1-c\" transform=\"rotate(144)\"/></g><use width=\"100%\" height=\"100%\" y=\"-24\" href=\"#hata-uz-1x1-d\"/><use width=\"100%\" height=\"100%\" y=\"-48\" href=\"#hata-uz-1x1-d\"/></g><use width=\"100%\" height=\"100%\" x=\"24\" href=\"#hata-uz-1x1-e\"/><use width=\"100%\" height=\"100%\" x=\"48\" href=\"#hata-uz-1x1-e\"/><use width=\"100%\" height=\"100%\" x=\"-48\" href=\"#hata-uz-1x1-d\"/><use width=\"100%\" height=\"100%\" x=\"-24\" href=\"#hata-uz-1x1-d\"/><use width=\"100%\" height=\"100%\" x=\"-24\" y=\"-24\" href=\"#hata-uz-1x1-d\"/></g></svg>";

export { svg };
export default svg;
