// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/uz.svg

/**
 * The flag of Uzbekistan (ウズベキスタン), UZ, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 1.3 KB.
 * The drawing `flag("UZ", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/uz.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><path fill=\"#1eb53a\" d=\"M0 320h640v160H0z\"/><path fill=\"#0099b5\" d=\"M0 0h640v160H0z\"/><path fill=\"#ce1126\" d=\"M0 153.6h640v172.8H0z\"/><path fill=\"#fff\" d=\"M0 163.2h640v153.6H0z\"/><circle cx=\"134.4\" cy=\"76.8\" r=\"57.6\" fill=\"#fff\"/><circle cx=\"153.6\" cy=\"76.8\" r=\"57.6\" fill=\"#0099b5\"/><g fill=\"#fff\" transform=\"translate(261.1 122.9)scale(1.92)\"><g id=\"hata-uz-4x3-e\"><g id=\"hata-uz-4x3-d\"><g id=\"hata-uz-4x3-c\"><g id=\"hata-uz-4x3-b\"><path id=\"hata-uz-4x3-a\" d=\"M0-6-1.9-.3 1 .7\"/><use width=\"100%\" height=\"100%\" href=\"#hata-uz-4x3-a\" transform=\"scale(-1 1)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-uz-4x3-b\" transform=\"rotate(72)\"/></g><use width=\"100%\" height=\"100%\" href=\"#hata-uz-4x3-b\" transform=\"rotate(-72)\"/><use width=\"100%\" height=\"100%\" href=\"#hata-uz-4x3-c\" transform=\"rotate(144)\"/></g><use width=\"100%\" height=\"100%\" y=\"-24\" href=\"#hata-uz-4x3-d\"/><use width=\"100%\" height=\"100%\" y=\"-48\" href=\"#hata-uz-4x3-d\"/></g><use width=\"100%\" height=\"100%\" x=\"24\" href=\"#hata-uz-4x3-e\"/><use width=\"100%\" height=\"100%\" x=\"48\" href=\"#hata-uz-4x3-e\"/><use width=\"100%\" height=\"100%\" x=\"-48\" href=\"#hata-uz-4x3-d\"/><use width=\"100%\" height=\"100%\" x=\"-24\" href=\"#hata-uz-4x3-d\"/><use width=\"100%\" height=\"100%\" x=\"-24\" y=\"-24\" href=\"#hata-uz-4x3-d\"/></g></svg>";

export { svg };
export default svg;
