// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/vc.svg

/**
 * The flag of St. Vincent & Grenadines (セントビンセント及びグレナディーン諸島), VC, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 382 B.
 * The drawing `flag("VC", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/vc.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><g fill-rule=\"evenodd\"><path fill=\"#f4f100\" d=\"M0 0h640v480H0z\"/><path fill=\"#199a00\" d=\"M490 0h150v480H490z\"/><path fill=\"#0058aa\" d=\"M0 0h150v480H0z\"/><path fill=\"#199a00\" d=\"m259.3 130-46.4 71.3 44.7 74.4 43.8-73.7zm121.2 0-46.3 71.3 44.7 74.4 43.8-73.7zm-61.2 97.3-46.4 71.4 44.8 74.4 43.8-73.7-42.2-72z\"/></g></svg>";

export { svg };
export default svg;
