// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Saint_Vincent_and_the_Grenadines.svg

/**
 * The flag of St. Vincent & Grenadines (セントビンセント及びグレナディーン諸島), VC, as an SVG string: viewBox 240 by 160 (3:2), 342 B.
 * From Wikimedia Commons, "Flag of Saint Vincent and the Grenadines.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/vc";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"vc\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 160\"><title>Flag of Saint Vincent and the Grenadines</title><path fill=\"#fcd022\" d=\"M0 0h240v160H0z\"/><path fill=\"#002674\" d=\"M0 0h60v160H0z\"/><path fill=\"#007c2e\" d=\"M180 0h60v160h-60zm-78 52 15 26-15 26-15-26zm36 0 15 26-15 26-15-26zm-18 31 15 26-15 26-15-26z\"/></svg>";

export { svg };
export default svg;
