// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3/ve.svg

/**
 * The flag of Venezuela (ベネズエラ), VE, drawn again by hand at 4:3 by flag-icons 7.5.0 (MIT), as an SVG string: viewBox 640 by 480, 1.1 KB.
 * The drawing `flag("VE", { shape: "4:3" })` uses, made for that shape by hand rather than cut from the flag. The /manifest entry's `framings` say how each frame was chosen.
 *
 * @example
 * ```ts
 * import square from "@johnmorrisdotca/hata/flags/ve.4x3";
 *
 * element.innerHTML = square;
 * ```
 */
const svg: string = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 480\"><defs><g id=\"hata-ve-4x3-d\" transform=\"translate(0 -36)\"><g id=\"hata-ve-4x3-c\"><g id=\"hata-ve-4x3-b\"><path id=\"hata-ve-4x3-a\" fill=\"#fff\" d=\"M0-5-1.5-.2l2.8.9z\"/><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-a\" transform=\"scale(-1 1)\"/></g><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-b\" transform=\"rotate(72)\"/></g><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-b\" transform=\"rotate(-72)\"/><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-c\" transform=\"rotate(144)\"/></g></defs><path fill=\"#cf142b\" d=\"M0 0h640v480H0z\"/><path fill=\"#00247d\" d=\"M0 0h640v320H0z\"/><path fill=\"#fc0\" d=\"M0 0h640v160H0z\"/><g id=\"hata-ve-4x3-f\" transform=\"matrix(4 0 0 4 320 336)\"><g id=\"hata-ve-4x3-e\"><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-d\" transform=\"rotate(10)\"/><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-d\" transform=\"rotate(30)\"/></g><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-e\" transform=\"rotate(40)\"/></g><use width=\"180\" height=\"120\" href=\"#hata-ve-4x3-f\" transform=\"rotate(-80 320 336)\"/></svg>";

export { svg };
export default svg;
