// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Vanuatu.svg

/**
 * The flag of Vanuatu (バヌアツ), VU, as an SVG string: viewBox 950 by 570 (5:3), 1.7 KB.
 * From Wikimedia Commons, "Flag of Vanuatu.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/vu";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"vu\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 950 570\"><path fill=\"#d21034\" d=\"M0 0h950v285H0z\"/><path fill=\"#009543\" d=\"M0 285h950v285H0z\"/><path d=\"m0 0 552.8 285L0 570z\"/><path d=\"M0 234h950v102H0z\"/><path fill=\"#fdce12\" d=\"M0 40.5 474.3 285 0 529.5z\"/><path fill=\"#fdce12\" d=\"M0 270h950v30H0z\"/><path d=\"M0 74.3 408.8 285 0 495.7z\"/><path fill=\"#fdce12\" d=\"M115.5 339.5V372a86 86 0 0 0 83.7-91.4c0-69.7-59.2-82.6-76.9-82.6-17.6 0-72.3 12.7-72.3 69.7s53.6 62.3 64.2 62.3c10.5 0 50.1-9.5 45.6-52.3a42.6 42.6 0 0 1-42.5 37.8c-28.8 0-46.7-21.4-46.7-42.5s17.4-49.4 47.8-49.4 52.5 27 52.5 54.1-21.4 61.8-55.4 61.8\"/><g id=\"hata-vu-a\" fill=\"#fdce12\"><path stroke=\"#fdce12\" d=\"m90.7 297.2 1.7 1.1s13.4-30.5 49.3-52.1c-4.5 2.4-28.6 14.4-51 51z\"/><path d=\"M94.2 292s-4.2-8.5-.5-12.3c3.7-3.7 2 10 2 10l1.6-2.3s-2.5-10.4.3-12.5c2.7-2.2 1.3 10 1.3 10l1.7-2.2s-1.8-10.1 1-12c2.6-1.9 1 9.5 1 9.5l1.9-2.3s-1.5-9.6 1.8-11.8.4 9 .4 9l2.1-2.3s-1-8.8 1.8-10.8.4 8.3.4 8.3l2-2s-.6-8.3 2-10.2c2.8-1.8.3 7.9.3 7.9l2-2s-.4-8.2 3-9.8c3.3-1.6-.7 7.7-.7 7.7l2.3-2s.7-9.6 3.6-10.5-1.3 8.5-1.3 8.5l2-1.6s1.2-8.3 4.3-9.3c3.2-1-2 7.6-2 7.6l2.1-1.6s2.3-8.2 5.3-9.1-3 7.7-3 7.7l1.9-1.4s3.3-7.4 6-8c2.6-.4-3 6.2-3 6.2l2.4-1.5s4.3-7.7 5.8-5.3-6 5.8-6 5.8l-2.4 1.4s9-4.2 10-2c1.2 2.1-12.3 3.5-12.3 3.5l-2.2 1.5s9-2.5 8-.2c-1.2 2.3-10 1.8-10 1.8l-2.2 1.5s9-2.2 7.9-.1c-1.2 2-10 1.8-10 1.8l-2.2 1.8s8.8-2.2 7.5.4c-1.3 2.7-11.3 2.6-11.3 2.6l-2.4 2.3s9.3-3.2 8.5-.7-11.4 3.7-11.4 3.7l-2.4 2.4s10-3.3 7-.3c-3 3.1-10.2 3.9-10.2 3.9l-2.8 3.5s9.9-6 8.5-2.6c-1.4 3.3-11.1 5.6-11.1 5.6l-2 2.4s9-5.1 8-2.3c-.9 2.9-10.4 6-10.4 6l-1.5 2.1s10.4-6.2 9.6-3c-1 3.1-11 5.4-11 5.4l-1.2 2s9.7-5.5 9.8-2.9c0 2.7-11.4 5.4-11.4 5.4z\"/></g><use href=\"#hata-vu-a\" transform=\"translate(238.5) scale(-1,1)\"/></svg>";

export { svg };
export default svg;
