// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Wallis_and_Futuna.svg

/**
 * The local flag of Wallis and Futuna: one of the flags of Wallis & Futuna (ウォリス・フツナ), WF, in real use, as an SVG string: viewBox 150 by 100 (3:2), 413 B.
 * From Wikimedia Commons, "Flag of Wallis and Futuna.svg" (public domain). `flag("WF", { variant: "local" })` loads it, and `variantsOf("WF")` says its status, dates and why it is offered.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/wf--local";
 *
 * element.innerHTML = flag;
 * ```
 */
const svg: string = "<svg data-hata=\"wf--local\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 150 100\"><path fill=\"#ce1126\" d=\"M0 0h150v100H0z\" style=\"fill:#ce1126;fill-opacity:1\"/><path fill=\"#fff\" d=\"M0 0h40v40H0z\"/><path fill=\"#002654\" d=\"M0 0h20v40H0z\" style=\"fill:#002654;fill-opacity:1\"/><path fill=\"none\" stroke=\"#fff\" d=\"M0 40h60V0\"/><path fill=\"#fff\" d=\"M105 46 93 34h24zm-4 4L89 38v24zm4 4L93 66h24zm4-4 12-12v24z\"/></svg>";

export { svg };
export default svg;
