// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Source: https://commons.wikimedia.org/wiki/File:Flag_of_Wallis_and_Futuna.svg

/**
 * The flag of Wallis & Futuna (ウォリス・フツナ), WF, as an SVG string: viewBox 150 by 100 (3:2), 406 B.
 * From Wikimedia Commons, "Flag of Wallis and Futuna.svg" (public domain); the /manifest entry gives its author, licence and why it was chosen.
 * It has a viewBox and no width or height, so it fills the box it is put in at its own aspect ratio.
 *
 * @example
 * ```ts
 * import flag from "@johnmorrisdotca/hata/flags/wf";
 *
 * element.innerHTML = flag; // or toDataUri(flag) from "@johnmorrisdotca/hata" for an <img src>
 * ```
 */
const svg: string = "<svg data-hata=\"wf\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 150 100\"><path fill=\"#ce1126\" d=\"M0 0h150v100H0z\" style=\"fill:#ce1126;fill-opacity:1\"/><path fill=\"#fff\" d=\"M0 0h40v40H0z\"/><path fill=\"#002654\" d=\"M0 0h20v40H0z\" style=\"fill:#002654;fill-opacity:1\"/><path fill=\"none\" stroke=\"#fff\" d=\"M0 40h60V0\"/><path fill=\"#fff\" d=\"M105 46 93 34h24zm-4 4L89 38v24zm4 4L93 66h24zm4-4 12-12v24z\"/></svg>";

export { svg };
export default svg;
